exclude = [
    "python_not_for_dunedaq/druncschema.egg-info",
    "python_not_for_dunedaq/*/*_pb2.py*",
    "python_not_for_dunedaq/*/*_pb2_grpc.py",
]

[lint]
select = [
    "F",  # PyFlakes
    "I"   # Isort
]
