#!/bin/bash
for FILE in schema/druncschema/*.proto;
do
    echo "Generating protocols for ${FILE}"
    python -m grpc_tools.protoc -I./schema/ --python_out=python_not_for_dunedaq/ --grpc_python_out=python_not_for_dunedaq/ --mypy_out=python_not_for_dunedaq/ --plugin=protoc-gen-mypy=$(which protoc-gen-mypy) ${FILE}
    FILE_NAME=$(basename -- "$FILE")
    CLASS_NAME="${FILE_NAME%.*}"
done
for FILE in schema/druncschema/opmon/*.proto;
do
    echo "Generating protocols for ${FILE}"
    python -m grpc_tools.protoc -I./schema/ --python_out=python_not_for_dunedaq/ --grpc_python_out=python_not_for_dunedaq/ --mypy_out=python_not_for_dunedaq/ --plugin=protoc-gen-mypy=$(which protoc-gen-mypy) ${FILE}
    FILE_NAME=$(basename -- "$FILE")
    CLASS_NAME="${FILE_NAME%.*}"
done