[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[project]
authors = [
  {name = "Pierre Lasorak", email = "p.lasorak@imperial.ac.uk"},
  {name = "Pawel Plesniak", email = "pawel.plesniak15@imperial.ac.uk"},
  {name = "Claudia Su", email = "claudia.su@physics.ox.ac.uk"},
]
dependencies = [
  "click",
  "grpcio",
  "grpcio-status",
  "grpcio-tools",
  "googleapis-common-protos",
  "rich",
]
description = "Schema definitions and compilation script for drunc"
name = "druncschema"
readme = "docs/README.md"
requires-python = ">=3.10"
version = "1.1.0"

[project.optional-dependencies]
dev = ["ruff", "pre-commit", "pytest", "pytest-cov", "mypy-protobuf", "types-protobuf"]

[project.urls]
Documentation = "https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-release/team_repos/?h=druncschema"
Repository = "https://github.com/DUNE-DAQ/druncschema"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=druncschema --cov=src/druncschema tests/"

[tool.coverage.run]
omit = ["tests/*", "scripts/*"]
source = ["druncschema"]

[tool.ruff]
exclude = [
  "src/druncschema.egg-info",
  "src/druncschema/*_pb2.py*",
  "src/druncschema/*_pb2_grpc.py*",
]

[tool.ruff.lint]
pydocstyle.convention = "google"
select = [
  "D", # pydocstyle
  "E", # pycodestyle
  "F", # Pyflakes
  "I", # isort
  "UP", # pyupgrade
  "RUF", # ruff-specific rules
  "R", # refactoring suggestions
]
