[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "druncschema"
description = "Schema definitions and compilation script for drunc"
version = "1.1.0"
readme = "docs/README.md"
requires-python = ">=3.10"
dependencies = [
    "click",
    "grpcio",
    "grpcio-status",
    "grpcio-tools",
    "googleapis-common-protos",
    "rich",
]
authors = [
    {name = "Pierre Lasorak", email = "p.lasorak@imperial.ac.uk"},
    {name = "Pawel Plesniak", email = "pawel.plesniak15@imperial.ac.uk"},
    {name = "Claudia Su", email = "claudia.su@physics.ox.ac.uk"}
]

[project.optional-dependencies]
dev = ["ruff", "pre-commit", "pytest", "pytest-cov", "mypy-protobuf", "types-protobuf"]

[project.urls]
Documentation = "https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-release/team_repos/?h=druncschema"
Repository = "https://github.com/DUNE-DAQ/druncschema"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=druncschema --cov=src/druncschema tests/"

[tool.coverage.run]
source = ["druncschema"]
omit = ["tests/*", "scripts/*"]


[tool.ruff]
exclude = [
    "src/druncschema.egg-info",
    "src/druncschema/*_pb2.py*",
    "src/druncschema/*_pb2_grpc.py",
]

[tool.ruff.lint]
select = [
    "D",   # pydocstyle
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
    "R",   # refactoring suggestions
]
pydocstyle.convention = "google"
