python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       authoriser.proto   
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       broadcast.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       controller.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       generic.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       process_manager.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       request_response.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       session_manager.proto 
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema       --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema       token.proto 

# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema/opmon --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon process_manager.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema/opmon --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon generic.proto
# python -m grpc_tools.protoc -I/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema --proto_path=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/schema/druncschema/opmon --python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon --grpc_python_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon --mypy_out=/nfs/home/pplesnia/nightlyDev/250408/sourcecode/druncschema/python_not_for_dunedaq/druncschema/opmon FSM.proto
Ÿ