"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from druncschema import token_pb2 as _token_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ActionType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ActionTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ActionType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CREATE: _ActionType.ValueType  # 0
    READ: _ActionType.ValueType  # 1
    UPDATE: _ActionType.ValueType  # 2
    DELETE: _ActionType.ValueType  # 3
    EXPERT: _ActionType.ValueType  # 4

class ActionType(_ActionType, metaclass=_ActionTypeEnumTypeWrapper): ...

CREATE: ActionType.ValueType  # 0
READ: ActionType.ValueType  # 1
UPDATE: ActionType.ValueType  # 2
DELETE: ActionType.ValueType  # 3
EXPERT: ActionType.ValueType  # 4
Global___ActionType: _TypeAlias = ActionType  # noqa: Y015

class _SystemType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SystemTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SystemType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CONTROLLER: _SystemType.ValueType  # 0
    APPLICATION: _SystemType.ValueType  # 1
    PROCESS_MANAGER: _SystemType.ValueType  # 2
    SESSION_MANAGER: _SystemType.ValueType  # 3
    RESOURCE_MANAGER: _SystemType.ValueType  # 4
    AUTHORISER_SERVICE: _SystemType.ValueType  # 5

class SystemType(_SystemType, metaclass=_SystemTypeEnumTypeWrapper): ...

CONTROLLER: SystemType.ValueType  # 0
APPLICATION: SystemType.ValueType  # 1
PROCESS_MANAGER: SystemType.ValueType  # 2
SESSION_MANAGER: SystemType.ValueType  # 3
RESOURCE_MANAGER: SystemType.ValueType  # 4
AUTHORISER_SERVICE: SystemType.ValueType  # 5
Global___SystemType: _TypeAlias = SystemType  # noqa: Y015

@_typing.final
class AuthoriserRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    SYSTEM_FIELD_NUMBER: _builtins.int
    action: Global___ActionType.ValueType
    system: Global___SystemType.ValueType
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        action: Global___ActionType.ValueType = ...,
        system: Global___SystemType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "system", b"system", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthoriserRequest: _TypeAlias = AuthoriserRequest  # noqa: Y015
