# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authoriser.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import druncschema.token_pb2 as token__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61uthoriser.proto\x1a\x0btoken.proto\"d\n\x11\x41uthoriserRequest\x12\x15\n\x05token\x18\x01 \x01(\x0b\x32\x06.Token\x12\x1b\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x0b.ActionType\x12\x1b\n\x06system\x18\x03 \x01(\x0e\x32\x0b.SystemType*?\n\nActionType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04READ\x10\x01\x12\n\n\x06\x43REATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03*1\n\nSystemType\x12\x0e\n\nCONTROLLER\x10\x00\x12\x13\n\x0fPROCESS_MANAGER\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authoriser_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONTYPE._serialized_start=135
  _ACTIONTYPE._serialized_end=198
  _SYSTEMTYPE._serialized_start=200
  _SYSTEMTYPE._serialized_end=249
  _AUTHORISERREQUEST._serialized_start=33
  _AUTHORISERREQUEST._serialized_end=133
# @@protoc_insertion_point(module_scope)
