# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import druncschema.generic_pb2 as generic__pb2
import druncschema.request_response_pb2 as request__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62roadcast.proto\x12\x05\x44runc\x1a\x19google/protobuf/any.proto\x1a\rgeneric.proto\x1a\x16request_response.proto\"k\n\x10\x42roadcastMessage\x12\x0f\n\x07\x65mitter\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.Drunc.BroadcastType\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"6\n\x10\x42roadcastRequest\x12\"\n\x1a\x62roadcast_receiver_address\x18\x01 \x01(\t\"$\n\x11\x42roadcastResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*\x8c\x02\n\rBroadcastType\x12\x07\n\x03\x41\x43K\x10\x00\x12\x14\n\x10RECEIVER_REMOVED\x10\x01\x12\x12\n\x0eRECEIVER_ADDED\x10\x02\x12\x13\n\x0fSERVER_SHUTDOWN\x10\x03\x12\x10\n\x0cTEXT_MESSAGE\x10\x04\x12\x1b\n\x17\x43OMMAND_EXECUTION_START\x10\x05\x12\x1d\n\x19\x43OMMAND_EXECUTION_SUCCESS\x10\x06\x12\x14\n\x10\x45XCEPTION_RAISED\x10\x07\x12\x1e\n\x1aUNHANDLED_EXCEPTION_RAISED\x10\x08\x12\x11\n\rSTATUS_UPDATE\x10\t\x12\x1c\n\x18SUBPROCESS_STATUS_UPDATE\x10\n2J\n\x11\x42roadcastReceiver\x12\x35\n\x10handle_broadcast\x12\x17.Drunc.BroadcastMessage\x1a\x06.Empty\"\x00\x32\xa3\x01\n\x0f\x42roadcastSender\x12.\n\x15\x61\x64\x64_to_broadcast_list\x12\x08.Request\x1a\t.Response\"\x00\x12\x33\n\x1aremove_from_broadcast_list\x12\x08.Request\x1a\t.Response\"\x00\x12+\n\x12get_broadcast_list\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broadcast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BROADCASTTYPE._serialized_start=296
  _BROADCASTTYPE._serialized_end=564
  _BROADCASTMESSAGE._serialized_start=92
  _BROADCASTMESSAGE._serialized_end=199
  _BROADCASTREQUEST._serialized_start=201
  _BROADCASTREQUEST._serialized_end=255
  _BROADCASTRESPONSE._serialized_start=257
  _BROADCASTRESPONSE._serialized_end=293
  _BROADCASTRECEIVER._serialized_start=566
  _BROADCASTRECEIVER._serialized_end=640
  _BROADCASTSENDER._serialized_start=643
  _BROADCASTSENDER._serialized_end=806
# @@protoc_insertion_point(module_scope)
