"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BroadcastType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BroadcastTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BroadcastType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACK: _BroadcastType.ValueType  # 0
    RECEIVER_REMOVED: _BroadcastType.ValueType  # 1
    RECEIVER_ADDED: _BroadcastType.ValueType  # 2
    SERVER_READY: _BroadcastType.ValueType  # 3
    SERVER_SHUTDOWN: _BroadcastType.ValueType  # 4
    TEXT_MESSAGE: _BroadcastType.ValueType  # 15
    COMMAND_EXECUTION_START: _BroadcastType.ValueType  # 5
    COMMAND_RECEIVED: _BroadcastType.ValueType  # 16
    COMMAND_EXECUTION_SUCCESS: _BroadcastType.ValueType  # 6
    DRUNC_EXCEPTION_RAISED: _BroadcastType.ValueType  # 7
    UNHANDLED_EXCEPTION_RAISED: _BroadcastType.ValueType  # 8
    STATUS_UPDATE: _BroadcastType.ValueType  # 9
    SUBPROCESS_STATUS_UPDATE: _BroadcastType.ValueType  # 10
    DEBUG: _BroadcastType.ValueType  # 11
    CHILD_COMMAND_EXECUTION_START: _BroadcastType.ValueType  # 12
    CHILD_COMMAND_EXECUTION_SUCCESS: _BroadcastType.ValueType  # 13
    CHILD_COMMAND_EXECUTION_FAILED: _BroadcastType.ValueType  # 14
    FSM_STATUS_UPDATE: _BroadcastType.ValueType  # 17

class BroadcastType(_BroadcastType, metaclass=_BroadcastTypeEnumTypeWrapper): ...

ACK: BroadcastType.ValueType  # 0
RECEIVER_REMOVED: BroadcastType.ValueType  # 1
RECEIVER_ADDED: BroadcastType.ValueType  # 2
SERVER_READY: BroadcastType.ValueType  # 3
SERVER_SHUTDOWN: BroadcastType.ValueType  # 4
TEXT_MESSAGE: BroadcastType.ValueType  # 15
COMMAND_EXECUTION_START: BroadcastType.ValueType  # 5
COMMAND_RECEIVED: BroadcastType.ValueType  # 16
COMMAND_EXECUTION_SUCCESS: BroadcastType.ValueType  # 6
DRUNC_EXCEPTION_RAISED: BroadcastType.ValueType  # 7
UNHANDLED_EXCEPTION_RAISED: BroadcastType.ValueType  # 8
STATUS_UPDATE: BroadcastType.ValueType  # 9
SUBPROCESS_STATUS_UPDATE: BroadcastType.ValueType  # 10
DEBUG: BroadcastType.ValueType  # 11
CHILD_COMMAND_EXECUTION_START: BroadcastType.ValueType  # 12
CHILD_COMMAND_EXECUTION_SUCCESS: BroadcastType.ValueType  # 13
CHILD_COMMAND_EXECUTION_FAILED: BroadcastType.ValueType  # 14
FSM_STATUS_UPDATE: BroadcastType.ValueType  # 17
global___BroadcastType = BroadcastType

@typing.final
class KafkaBroadcastHandlerConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KAFKA_ADDRESS_FIELD_NUMBER: builtins.int
    TOPIC_FIELD_NUMBER: builtins.int
    kafka_address: builtins.str
    topic: builtins.str
    def __init__(
        self,
        *,
        kafka_address: builtins.str = ...,
        topic: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["kafka_address", b"kafka_address", "topic", b"topic"]) -> None: ...

global___KafkaBroadcastHandlerConfiguration = KafkaBroadcastHandlerConfiguration

@typing.final
class Emitter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROCESS_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    process: builtins.str
    session: builtins.str
    def __init__(
        self,
        *,
        process: builtins.str = ...,
        session: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["process", b"process", "session", b"session"]) -> None: ...

global___Emitter = Emitter

@typing.final
class BroadcastMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMITTER_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    type: global___BroadcastType.ValueType
    @property
    def emitter(self) -> global___Emitter: ...
    @property
    def data(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        emitter: global___Emitter | None = ...,
        type: global___BroadcastType.ValueType = ...,
        data: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "emitter", b"emitter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "emitter", b"emitter", "type", b"type"]) -> None: ...

global___BroadcastMessage = BroadcastMessage

@typing.final
class BroadcastRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BROADCAST_RECEIVER_ADDRESS_FIELD_NUMBER: builtins.int
    broadcast_receiver_address: builtins.str
    def __init__(
        self,
        *,
        broadcast_receiver_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["broadcast_receiver_address", b"broadcast_receiver_address"]) -> None: ...

global___BroadcastRequest = BroadcastRequest

@typing.final
class BroadcastResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

global___BroadcastResponse = BroadcastResponse
