# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: druncschema/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'druncschema/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from druncschema import generic_pb2 as druncschema_dot_generic__pb2
from druncschema import token_pb2 as druncschema_dot_token__pb2
from druncschema import request_response_pb2 as druncschema_dot_request__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64runcschema/common.proto\x12\x13\x64unedaq.druncschema\x1a\x19\x64runcschema/generic.proto\x1a\x17\x64runcschema/token.proto\x1a\"druncschema/request_response.proto\"\xb7\x01\n\nLogRequest\x12)\n\x05token\x18\x01 \x01(\x0b\x32\x1a.dunedaq.druncschema.Token\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x0e\n\x06target\x18\x04 \x01(\t\x12\x1a\n\x12\x65xecute_along_path\x18\x05 \x01(\x08\x12\x32\n*execute_on_all_subsequent_children_in_path\x18\x06 \x01(\x08\"\xab\x01\n\x0bLogResponse\x12)\n\x05token\x18\x01 \x01(\x0b\x32\x1a.dunedaq.druncschema.Token\x12\x0c\n\x04name\x18\x02 \x01(\t\x12/\n\x04\x66lag\x18\x03 \x01(\x0e\x32!.dunedaq.druncschema.ResponseFlag\x12\x32\n\x08\x63hildren\x18\x04 \x03(\x0b\x32 .dunedaq.druncschema.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'druncschema.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=138
  _globals['_LOGREQUEST']._serialized_end=321
  _globals['_LOGRESPONSE']._serialized_start=324
  _globals['_LOGRESPONSE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
