# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
import druncschema.request_response_pb2 as request__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\x05\x44runc\x1a\x19google/protobuf/any.proto\x1a\x16request_response.proto\"+\n\x08Location\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\"2\n\x0cLocationList\x12\"\n\tlocations\x18\x01 \x03(\x0b\x32\x0f.Drunc.Location\"k\n\x0fStringStringMap\x12,\n\x03map\x18\x01 \x03(\x0b\x32\x1f.Drunc.StringStringMap.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"o\n\x0f\x43ommandResponse\x12\x1f\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x0e.Drunc.Command\x12\x14\n\x0c\x63ommand_code\x18\x02 \x01(\x05\x12%\n\x07payload\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"I\n\x07\x43ommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\targuments\x18\x02 \x03(\x0b\x32\x0f.Drunc.Argument\x12\x0c\n\x04help\x18\x03 \x01(\t\"9\n\x16ListOfCommandsResponse\x12\x1f\n\x07\x63ommand\x18\x02 \x03(\x0b\x32\x0e.Drunc.Command\"\xc7\x01\n\x08\x41rgument\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.Drunc.Argument.ArgumentType\x12!\n\x03\x64\x65\x66\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12#\n\x05value\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x0c\n\x04help\x18\x05 \x01(\t\"+\n\x0c\x41rgumentType\x12\r\n\tMANDATORY\x10\x00\x12\x0c\n\x08OPTIONAL\x10\x01\x32\x8e\x03\n\nController\x12\x1b\n\x02ls\x12\x08.Request\x1a\t.Response\"\x00\x12.\n\x15\x61\x64\x64_to_broadcast_list\x12\x08.Request\x1a\t.Response\"\x00\x12\x33\n\x1aremove_from_broadcast_list\x12\x08.Request\x1a\t.Response\"\x00\x12+\n\x12get_broadcast_list\x12\x08.Request\x1a\t.Response\"\x00\x12)\n\x10get_command_list\x12\x08.Request\x1a\t.Response\"\x00\x12(\n\x0f\x65xecute_command\x12\x08.Request\x1a\t.Response\"\x00\x12%\n\x0ctake_control\x12\x08.Request\x1a\t.Response\"\x00\x12*\n\x11surrender_control\x12\x08.Request\x1a\t.Response\"\x00\x12)\n\x10who_is_in_charge\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGSTRINGMAP_MAPENTRY._options = None
  _STRINGSTRINGMAP_MAPENTRY._serialized_options = b'8\001'
  _LOCATION._serialized_start=78
  _LOCATION._serialized_end=121
  _LOCATIONLIST._serialized_start=123
  _LOCATIONLIST._serialized_end=173
  _STRINGSTRINGMAP._serialized_start=175
  _STRINGSTRINGMAP._serialized_end=282
  _STRINGSTRINGMAP_MAPENTRY._serialized_start=240
  _STRINGSTRINGMAP_MAPENTRY._serialized_end=282
  _COMMANDRESPONSE._serialized_start=284
  _COMMANDRESPONSE._serialized_end=395
  _COMMAND._serialized_start=397
  _COMMAND._serialized_end=470
  _LISTOFCOMMANDSRESPONSE._serialized_start=472
  _LISTOFCOMMANDSRESPONSE._serialized_end=529
  _ARGUMENT._serialized_start=532
  _ARGUMENT._serialized_end=731
  _ARGUMENT_ARGUMENTTYPE._serialized_start=688
  _ARGUMENT_ARGUMENTTYPE._serialized_end=731
  _CONTROLLER._serialized_start=734
  _CONTROLLER._serialized_end=1132
# @@protoc_insertion_point(module_scope)
