"""@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
from grpc import aio as _aio

from druncschema import controller_pb2 as _controller_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(
    _abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta
): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ControllerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ControllerAsyncStub: ...
    describe: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.DescribeRequest, _controller_pb2.DescribeResponse
    ]
    status: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.StatusRequest, _controller_pb2.StatusResponse
    ]
    describe_fsm: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.DescribeFSMRequest, _controller_pb2.DescribeFSMResponse
    ]
    execute_fsm_command: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.ExecuteFSMCommandRequest,
        _controller_pb2.ExecuteFSMCommandResponse,
    ]
    execute_expert_command: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.ExecuteExpertCommandRequest,
        _controller_pb2.ExecuteExpertCommandResponse,
    ]
    include: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.IncludeRequest, _controller_pb2.IncludeResponse
    ]
    exclude: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.ExcludeRequest, _controller_pb2.ExcludeResponse
    ]
    recompute_status: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.RecomputeStatusRequest, _controller_pb2.RecomputeStatusResponse
    ]
    take_control: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.TakeControlRequest, _controller_pb2.TakeControlResponse
    ]
    surrender_control: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.SurrenderControlRequest,
        _controller_pb2.SurrenderControlResponse,
    ]
    who_is_in_charge: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.WhoIsInChargeRequest, _controller_pb2.WhoIsInChargeResponse
    ]
    to_error: _grpc.UnaryUnaryMultiCallable[
        _controller_pb2.ToErrorRequest, _controller_pb2.ToErrorResponse
    ]

@_typing.type_check_only
class ControllerAsyncStub(ControllerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    describe: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.DescribeRequest, _controller_pb2.DescribeResponse
    ]  # type: ignore[assignment]
    status: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.StatusRequest, _controller_pb2.StatusResponse
    ]  # type: ignore[assignment]
    describe_fsm: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.DescribeFSMRequest, _controller_pb2.DescribeFSMResponse
    ]  # type: ignore[assignment]
    execute_fsm_command: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.ExecuteFSMCommandRequest,
        _controller_pb2.ExecuteFSMCommandResponse,
    ]  # type: ignore[assignment]
    execute_expert_command: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.ExecuteExpertCommandRequest,
        _controller_pb2.ExecuteExpertCommandResponse,
    ]  # type: ignore[assignment]
    include: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.IncludeRequest, _controller_pb2.IncludeResponse
    ]  # type: ignore[assignment]
    exclude: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.ExcludeRequest, _controller_pb2.ExcludeResponse
    ]  # type: ignore[assignment]
    recompute_status: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.RecomputeStatusRequest, _controller_pb2.RecomputeStatusResponse
    ]  # type: ignore[assignment]
    take_control: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.TakeControlRequest, _controller_pb2.TakeControlResponse
    ]  # type: ignore[assignment]
    surrender_control: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.SurrenderControlRequest,
        _controller_pb2.SurrenderControlResponse,
    ]  # type: ignore[assignment]
    who_is_in_charge: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.WhoIsInChargeRequest, _controller_pb2.WhoIsInChargeResponse
    ]  # type: ignore[assignment]
    to_error: _aio.UnaryUnaryMultiCallable[
        _controller_pb2.ToErrorRequest, _controller_pb2.ToErrorResponse
    ]  # type: ignore[assignment]

class ControllerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def describe(
        self,
        request: _controller_pb2.DescribeRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.DescribeResponse
        | _abc.Awaitable[_controller_pb2.DescribeResponse]
    ): ...
    @_abc_1.abstractmethod
    def status(
        self,
        request: _controller_pb2.StatusRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.StatusResponse | _abc.Awaitable[_controller_pb2.StatusResponse]
    ): ...
    @_abc_1.abstractmethod
    def describe_fsm(
        self,
        request: _controller_pb2.DescribeFSMRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.DescribeFSMResponse
        | _abc.Awaitable[_controller_pb2.DescribeFSMResponse]
    ): ...
    @_abc_1.abstractmethod
    def execute_fsm_command(
        self,
        request: _controller_pb2.ExecuteFSMCommandRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.ExecuteFSMCommandResponse
        | _abc.Awaitable[_controller_pb2.ExecuteFSMCommandResponse]
    ): ...
    @_abc_1.abstractmethod
    def execute_expert_command(
        self,
        request: _controller_pb2.ExecuteExpertCommandRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.ExecuteExpertCommandResponse
        | _abc.Awaitable[_controller_pb2.ExecuteExpertCommandResponse]
    ): ...
    @_abc_1.abstractmethod
    def include(
        self,
        request: _controller_pb2.IncludeRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.IncludeResponse
        | _abc.Awaitable[_controller_pb2.IncludeResponse]
    ): ...
    @_abc_1.abstractmethod
    def exclude(
        self,
        request: _controller_pb2.ExcludeRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.ExcludeResponse
        | _abc.Awaitable[_controller_pb2.ExcludeResponse]
    ): ...
    @_abc_1.abstractmethod
    def recompute_status(
        self,
        request: _controller_pb2.RecomputeStatusRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.RecomputeStatusResponse
        | _abc.Awaitable[_controller_pb2.RecomputeStatusResponse]
    ): ...
    @_abc_1.abstractmethod
    def take_control(
        self,
        request: _controller_pb2.TakeControlRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.TakeControlResponse
        | _abc.Awaitable[_controller_pb2.TakeControlResponse]
    ): ...
    @_abc_1.abstractmethod
    def surrender_control(
        self,
        request: _controller_pb2.SurrenderControlRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.SurrenderControlResponse
        | _abc.Awaitable[_controller_pb2.SurrenderControlResponse]
    ): ...
    @_abc_1.abstractmethod
    def who_is_in_charge(
        self,
        request: _controller_pb2.WhoIsInChargeRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.WhoIsInChargeResponse
        | _abc.Awaitable[_controller_pb2.WhoIsInChargeResponse]
    ): ...
    @_abc_1.abstractmethod
    def to_error(
        self,
        request: _controller_pb2.ToErrorRequest,
        context: _ServicerContext,
    ) -> (
        _controller_pb2.ToErrorResponse
        | _abc.Awaitable[_controller_pb2.ToErrorResponse]
    ): ...

def add_ControllerServicer_to_server(
    servicer: ControllerServicer, server: _grpc.Server | _aio.Server
) -> None: ...
