"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import druncschema.description_pb2
import druncschema.request_response_pb2
import druncschema.token_pb2
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _FSMResponseFlag:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FSMResponseFlagEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FSMResponseFlag.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FSM_EXECUTED_SUCCESSFULLY: _FSMResponseFlag.ValueType  # 0
    FSM_FAILED: _FSMResponseFlag.ValueType  # 1
    FSM_INVALID_TRANSITION: _FSMResponseFlag.ValueType  # 2
    FSM_NOT_EXECUTED_EXCLUDED: _FSMResponseFlag.ValueType  # 3
    FSM_NOT_EXECUTED_IN_ERROR: _FSMResponseFlag.ValueType  # 4

class FSMResponseFlag(_FSMResponseFlag, metaclass=_FSMResponseFlagEnumTypeWrapper): ...

FSM_EXECUTED_SUCCESSFULLY: FSMResponseFlag.ValueType  # 0
FSM_FAILED: FSMResponseFlag.ValueType  # 1
FSM_INVALID_TRANSITION: FSMResponseFlag.ValueType  # 2
FSM_NOT_EXECUTED_EXCLUDED: FSMResponseFlag.ValueType  # 3
FSM_NOT_EXECUTED_IN_ERROR: FSMResponseFlag.ValueType  # 4
Global___FSMResponseFlag: typing_extensions.TypeAlias = FSMResponseFlag

@typing.final
class AddressedCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    COMMAND_NAME_FIELD_NUMBER: builtins.int
    COMMAND_DATA_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    command_name: builtins.str
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def command_data(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        command_name: builtins.str = ...,
        command_data: google.protobuf.any_pb2.Any | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_command_data", b"_command_data", "command_data", b"command_data", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_command_data", b"_command_data", "command_data", b"command_data", "command_name", b"command_name", "execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_command_data", b"_command_data"]) -> typing.Literal["command_data"] | None: ...

Global___AddressedCommand: typing_extensions.TypeAlias = AddressedCommand

@typing.final
class ExecuteExpertCommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    JSON_STRING_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    json_string: builtins.str
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        json_string: builtins.str = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "json_string", b"json_string", "target", b"target", "token", b"token"]) -> None: ...

Global___ExecuteExpertCommandRequest: typing_extensions.TypeAlias = ExecuteExpertCommandRequest

@typing.final
class ExecuteExpertCommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FSM_FLAG_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    data: builtins.str
    fsm_flag: Global___FSMResponseFlag.ValueType
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ExecuteExpertCommandResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        data: builtins.str = ...,
        children: collections.abc.Iterable[Global___ExecuteExpertCommandResponse] | None = ...,
        fsm_flag: Global___FSMResponseFlag.ValueType = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "data", b"data", "flag", b"flag", "fsm_flag", b"fsm_flag", "name", b"name", "token", b"token"]) -> None: ...

Global___ExecuteExpertCommandResponse: typing_extensions.TypeAlias = ExecuteExpertCommandResponse

@typing.final
class ExecuteFSMCommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def command(self) -> Global___FSMCommand: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        command: Global___FSMCommand | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___ExecuteFSMCommandRequest: typing_extensions.TypeAlias = ExecuteFSMCommandRequest

@typing.final
class ExecuteFSMCommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    COMMAND_NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FSM_FLAG_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    command_name: builtins.str
    data: builtins.str
    fsm_flag: Global___FSMResponseFlag.ValueType
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ExecuteFSMCommandResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        command_name: builtins.str = ...,
        data: builtins.str = ...,
        children: collections.abc.Iterable[Global___ExecuteFSMCommandResponse] | None = ...,
        fsm_flag: Global___FSMResponseFlag.ValueType = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "command_name", b"command_name", "data", b"data", "flag", b"flag", "fsm_flag", b"fsm_flag", "name", b"name", "token", b"token"]) -> None: ...

Global___ExecuteFSMCommandResponse: typing_extensions.TypeAlias = ExecuteFSMCommandResponse

@typing.final
class FSMCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ArgumentsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> google.protobuf.any_pb2.Any: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: google.protobuf.any_pb2.Any | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    COMMAND_NAME_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    command_name: builtins.str
    data: builtins.str
    @property
    def arguments(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, google.protobuf.any_pb2.Any]: ...
    def __init__(
        self,
        *,
        command_name: builtins.str = ...,
        arguments: collections.abc.Mapping[builtins.str, google.protobuf.any_pb2.Any] | None = ...,
        data: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_data", b"_data", "data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_data", b"_data", "arguments", b"arguments", "command_name", b"command_name", "data", b"data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_data", b"_data"]) -> typing.Literal["data"] | None: ...

Global___FSMCommand: typing_extensions.TypeAlias = FSMCommand

@typing.final
class IncludeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___IncludeRequest: typing_extensions.TypeAlias = IncludeRequest

@typing.final
class IncludeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    text: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___IncludeResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        text: builtins.str = ...,
        children: collections.abc.Iterable[Global___IncludeResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "flag", b"flag", "name", b"name", "text", b"text", "token", b"token"]) -> None: ...

Global___IncludeResponse: typing_extensions.TypeAlias = IncludeResponse

@typing.final
class ExcludeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___ExcludeRequest: typing_extensions.TypeAlias = ExcludeRequest

@typing.final
class ExcludeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    text: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ExcludeResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        text: builtins.str = ...,
        children: collections.abc.Iterable[Global___ExcludeResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "flag", b"flag", "name", b"name", "text", b"text", "token", b"token"]) -> None: ...

Global___ExcludeResponse: typing_extensions.TypeAlias = ExcludeResponse

@typing.final
class TakeControlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___TakeControlRequest: typing_extensions.TypeAlias = TakeControlRequest

@typing.final
class TakeControlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    text: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TakeControlResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        text: builtins.str = ...,
        children: collections.abc.Iterable[Global___TakeControlResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "flag", b"flag", "name", b"name", "text", b"text", "token", b"token"]) -> None: ...

Global___TakeControlResponse: typing_extensions.TypeAlias = TakeControlResponse

@typing.final
class StatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___StatusRequest: typing_extensions.TypeAlias = StatusRequest

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def status(self) -> Global___Status: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___StatusResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        status: Global___Status | None = ...,
        children: collections.abc.Iterable[Global___StatusResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["status", b"status", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "flag", b"flag", "name", b"name", "status", b"status", "token", b"token"]) -> None: ...

Global___StatusResponse: typing_extensions.TypeAlias = StatusResponse

@typing.final
class RecomputeStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___RecomputeStatusRequest: typing_extensions.TypeAlias = RecomputeStatusRequest

@typing.final
class RecomputeStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___RecomputeStatusResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        children: collections.abc.Iterable[Global___RecomputeStatusResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "flag", b"flag", "name", b"name", "token", b"token"]) -> None: ...

Global___RecomputeStatusResponse: typing_extensions.TypeAlias = RecomputeStatusResponse

@typing.final
class DescribeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "target", b"target", "token", b"token"]) -> None: ...

Global___DescribeRequest: typing_extensions.TypeAlias = DescribeRequest

@typing.final
class DescribeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def description(self) -> druncschema.description_pb2.Description: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___DescribeResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        description: druncschema.description_pb2.Description | None = ...,
        children: collections.abc.Iterable[Global___DescribeResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["description", b"description", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "description", b"description", "flag", b"flag", "name", b"name", "token", b"token"]) -> None: ...

Global___DescribeResponse: typing_extensions.TypeAlias = DescribeResponse

@typing.final
class DescribeFSMRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: builtins.int
    key: builtins.str
    target: builtins.str
    execute_along_path: builtins.bool
    execute_on_all_subsequent_children_in_path: builtins.bool
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        key: builtins.str = ...,
        target: builtins.str = ...,
        execute_along_path: builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "key", b"key", "target", b"target", "token", b"token"]) -> None: ...

Global___DescribeFSMRequest: typing_extensions.TypeAlias = DescribeFSMRequest

@typing.final
class DescribeFSMResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def description(self) -> Global___FSMCommandsDescription: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___DescribeFSMResponse]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        name: builtins.str = ...,
        description: Global___FSMCommandsDescription | None = ...,
        children: collections.abc.Iterable[Global___DescribeFSMResponse] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["description", b"description", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["children", b"children", "description", b"description", "flag", b"flag", "name", b"name", "token", b"token"]) -> None: ...

Global___DescribeFSMResponse: typing_extensions.TypeAlias = DescribeFSMResponse

@typing.final
class Argument(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Presence:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PresenceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Argument._Presence.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        MANDATORY: Argument._Presence.ValueType  # 0
        OPTIONAL: Argument._Presence.ValueType  # 1

    class Presence(_Presence, metaclass=_PresenceEnumTypeWrapper): ...
    MANDATORY: Argument.Presence.ValueType  # 0
    OPTIONAL: Argument.Presence.ValueType  # 1

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Argument._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INT: Argument._Type.ValueType  # 0
        FLOAT: Argument._Type.ValueType  # 1
        STRING: Argument._Type.ValueType  # 2
        BOOL: Argument._Type.ValueType  # 3

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    INT: Argument.Type.ValueType  # 0
    FLOAT: Argument.Type.ValueType  # 1
    STRING: Argument.Type.ValueType  # 2
    BOOL: Argument.Type.ValueType  # 3

    NAME_FIELD_NUMBER: builtins.int
    PRESENCE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DEFAULT_VALUE_FIELD_NUMBER: builtins.int
    CHOICES_FIELD_NUMBER: builtins.int
    HELP_FIELD_NUMBER: builtins.int
    name: builtins.str
    presence: Global___Argument.Presence.ValueType
    type: Global___Argument.Type.ValueType
    help: builtins.str
    @property
    def default_value(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def choices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        presence: Global___Argument.Presence.ValueType = ...,
        type: Global___Argument.Type.ValueType = ...,
        default_value: google.protobuf.any_pb2.Any | None = ...,
        choices: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
        help: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_default_value", b"_default_value", "default_value", b"default_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_default_value", b"_default_value", "choices", b"choices", "default_value", b"default_value", "help", b"help", "name", b"name", "presence", b"presence", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_default_value", b"_default_value"]) -> typing.Literal["default_value"] | None: ...

Global___Argument: typing_extensions.TypeAlias = Argument

@typing.final
class FSMCommandDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    HELP_FIELD_NUMBER: builtins.int
    RETURN_TYPE_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    name: builtins.str
    help: builtins.str
    return_type: builtins.str
    @property
    def data_type(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Argument]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        data_type: collections.abc.Iterable[builtins.str] | None = ...,
        help: builtins.str = ...,
        return_type: builtins.str = ...,
        arguments: collections.abc.Iterable[Global___Argument] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "data_type", b"data_type", "help", b"help", "name", b"name", "return_type", b"return_type"]) -> None: ...

Global___FSMCommandDescription: typing_extensions.TypeAlias = FSMCommandDescription

@typing.final
class FSMSequence(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    COMMAND_IDS_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def command_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        command_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["command_ids", b"command_ids", "id", b"id"]) -> None: ...

Global___FSMSequence: typing_extensions.TypeAlias = FSMSequence

@typing.final
class FSMCommandsDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    COMMANDS_FIELD_NUMBER: builtins.int
    SEQUENCES_FIELD_NUMBER: builtins.int
    type: builtins.str
    name: builtins.str
    session: builtins.str
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def commands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___FSMCommandDescription]: ...
    @property
    def sequences(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___FSMSequence]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        type: builtins.str = ...,
        name: builtins.str = ...,
        session: builtins.str | None = ...,
        commands: collections.abc.Iterable[Global___FSMCommandDescription] | None = ...,
        sequences: collections.abc.Iterable[Global___FSMSequence] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_session", b"_session", "session", b"session", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_session", b"_session", "commands", b"commands", "name", b"name", "sequences", b"sequences", "session", b"session", "token", b"token", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_session", b"_session"]) -> typing.Literal["session"] | None: ...

Global___FSMCommandsDescription: typing_extensions.TypeAlias = FSMCommandsDescription

@typing.final
class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    SUB_STATE_FIELD_NUMBER: builtins.int
    IN_ERROR_FIELD_NUMBER: builtins.int
    INCLUDED_FIELD_NUMBER: builtins.int
    RUN_INFO_FIELD_NUMBER: builtins.int
    state: builtins.str
    sub_state: builtins.str
    in_error: builtins.bool
    included: builtins.bool
    @property
    def run_info(self) -> Global___RunInfo: ...
    def __init__(
        self,
        *,
        state: builtins.str = ...,
        sub_state: builtins.str = ...,
        in_error: builtins.bool = ...,
        included: builtins.bool = ...,
        run_info: Global___RunInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_run_info", b"_run_info", "run_info", b"run_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_run_info", b"_run_info", "in_error", b"in_error", "included", b"included", "run_info", b"run_info", "state", b"state", "sub_state", b"sub_state"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_run_info", b"_run_info"]) -> typing.Literal["run_info"] | None: ...

Global___Status: typing_extensions.TypeAlias = Status

@typing.final
class RunInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_TYPE_FIELD_NUMBER: builtins.int
    TRIGGER_RATE_FIELD_NUMBER: builtins.int
    RUN_NUMBER_FIELD_NUMBER: builtins.int
    DISABLE_DATA_STORAGE_FIELD_NUMBER: builtins.int
    RUN_TIME_AT_START_FIELD_NUMBER: builtins.int
    RUN_TIME_SINCE_START_FIELD_NUMBER: builtins.int
    RUN_CONFIG_FILE_FIELD_NUMBER: builtins.int
    RUN_CONFIG_NAME_FIELD_NUMBER: builtins.int
    run_type: builtins.str
    trigger_rate: builtins.float
    run_number: builtins.int
    disable_data_storage: builtins.bool
    run_time_at_start: builtins.int
    run_time_since_start: builtins.int
    run_config_file: builtins.str
    run_config_name: builtins.str
    def __init__(
        self,
        *,
        run_type: builtins.str = ...,
        trigger_rate: builtins.float = ...,
        run_number: builtins.int = ...,
        disable_data_storage: builtins.bool = ...,
        run_time_at_start: builtins.int = ...,
        run_time_since_start: builtins.int = ...,
        run_config_file: builtins.str = ...,
        run_config_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["disable_data_storage", b"disable_data_storage", "run_config_file", b"run_config_file", "run_config_name", b"run_config_name", "run_number", b"run_number", "run_time_at_start", b"run_time_at_start", "run_time_since_start", b"run_time_since_start", "run_type", b"run_type", "trigger_rate", b"trigger_rate"]) -> None: ...

Global___RunInfo: typing_extensions.TypeAlias = RunInfo
