"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import druncschema.request_response_pb2
import druncschema.token_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ProcessRestriction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALLOWED_HOSTS_FIELD_NUMBER: builtins.int
    ALLOWED_HOST_TYPES_FIELD_NUMBER: builtins.int
    DATA_MOUNT_FIELD_NUMBER: builtins.int
    data_mount: builtins.str
    @property
    def allowed_hosts(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def allowed_host_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        allowed_hosts: collections.abc.Iterable[builtins.str] | None = ...,
        allowed_host_types: collections.abc.Iterable[builtins.str] | None = ...,
        data_mount: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_data_mount", b"_data_mount", "data_mount", b"data_mount"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_data_mount", b"_data_mount", "allowed_host_types", b"allowed_host_types", "allowed_hosts", b"allowed_hosts", "data_mount", b"data_mount"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_data_mount", b"_data_mount"]) -> typing.Literal["data_mount"] | None: ...

Global___ProcessRestriction: typing_extensions.TypeAlias = ProcessRestriction

@typing.final
class CommandNotificationMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    user: builtins.str
    command: builtins.str
    def __init__(
        self,
        *,
        user: builtins.str = ...,
        command: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "user", b"user"]) -> None: ...

Global___CommandNotificationMessage: typing_extensions.TypeAlias = CommandNotificationMessage

@typing.final
class GenericNotificationMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message"]) -> None: ...

Global___GenericNotificationMessage: typing_extensions.TypeAlias = GenericNotificationMessage

@typing.final
class ExceptionNotification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class StackLine(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LINE_TEXT_FIELD_NUMBER: builtins.int
        LINE_NUMBER_FIELD_NUMBER: builtins.int
        FILE_FIELD_NUMBER: builtins.int
        line_text: builtins.str
        line_number: builtins.str
        file: builtins.str
        def __init__(
            self,
            *,
            line_text: builtins.str = ...,
            line_number: builtins.str = ...,
            file: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["file", b"file", "line_number", b"line_number", "line_text", b"line_text"]) -> None: ...

    ERROR_TEXT_FIELD_NUMBER: builtins.int
    STACK_TRACE_FIELD_NUMBER: builtins.int
    error_text: builtins.str
    @property
    def stack_trace(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ExceptionNotification.StackLine]: ...
    def __init__(
        self,
        *,
        error_text: builtins.str = ...,
        stack_trace: collections.abc.Iterable[Global___ExceptionNotification.StackLine] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_text", b"error_text", "stack_trace", b"stack_trace"]) -> None: ...

Global___ExceptionNotification: typing_extensions.TypeAlias = ExceptionNotification

@typing.final
class LogRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    HOW_FAR_FIELD_NUMBER: builtins.int
    how_far: builtins.int
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def query(self) -> Global___ProcessQuery: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        query: Global___ProcessQuery | None = ...,
        how_far: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["query", b"query", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["how_far", b"how_far", "query", b"query", "token", b"token"]) -> None: ...

Global___LogRequest: typing_extensions.TypeAlias = LogRequest

@typing.final
class LogLines(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    LINES_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def uuid(self) -> Global___ProcessUUID: ...
    @property
    def lines(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        token: druncschema.token_pb2.Token | None = ...,
        uuid: Global___ProcessUUID | None = ...,
        lines: collections.abc.Iterable[builtins.str] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token", "uuid", b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["flag", b"flag", "lines", b"lines", "name", b"name", "token", b"token", "uuid", b"uuid"]) -> None: ...

Global___LogLines: typing_extensions.TypeAlias = LogLines

@typing.final
class ProcessUUID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    uuid: builtins.str
    def __init__(
        self,
        *,
        uuid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uuid", b"uuid"]) -> None: ...

Global___ProcessUUID: typing_extensions.TypeAlias = ProcessUUID

@typing.final
class ProcessMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UUID_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    TREE_ID_FIELD_NUMBER: builtins.int
    user: builtins.str
    session: builtins.str
    name: builtins.str
    hostname: builtins.str
    tree_id: builtins.str
    @property
    def uuid(self) -> Global___ProcessUUID: ...
    def __init__(
        self,
        *,
        uuid: Global___ProcessUUID | None = ...,
        user: builtins.str = ...,
        session: builtins.str | None = ...,
        name: builtins.str = ...,
        hostname: builtins.str = ...,
        tree_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_session", b"_session", "_tree_id", b"_tree_id", "session", b"session", "tree_id", b"tree_id", "uuid", b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_session", b"_session", "_tree_id", b"_tree_id", "hostname", b"hostname", "name", b"name", "session", b"session", "tree_id", b"tree_id", "user", b"user", "uuid", b"uuid"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_session", b"_session"]) -> typing.Literal["session"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tree_id", b"_tree_id"]) -> typing.Literal["tree_id"] | None: ...

Global___ProcessMetadata: typing_extensions.TypeAlias = ProcessMetadata

@typing.final
class ProcessQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    UUIDS_FIELD_NUMBER: builtins.int
    NAMES_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    user: builtins.str
    session: builtins.str
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def uuids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ProcessUUID]: ...
    @property
    def names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        uuids: collections.abc.Iterable[Global___ProcessUUID] | None = ...,
        names: collections.abc.Iterable[builtins.str] | None = ...,
        user: builtins.str = ...,
        session: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["names", b"names", "session", b"session", "token", b"token", "user", b"user", "uuids", b"uuids"]) -> None: ...

Global___ProcessQuery: typing_extensions.TypeAlias = ProcessQuery

@typing.final
class ProcessDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class StringList(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        VALUES_FIELD_NUMBER: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            values: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

    @typing.final
    class ExecAndArgs(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        EXEC_FIELD_NUMBER: builtins.int
        ARGS_FIELD_NUMBER: builtins.int
        exec: builtins.str
        @property
        def args(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            exec: builtins.str = ...,
            args: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["args", b"args", "exec", b"exec"]) -> None: ...

    @typing.final
    class EnvEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    METADATA_FIELD_NUMBER: builtins.int
    ENV_FIELD_NUMBER: builtins.int
    EXECUTABLE_AND_ARGUMENTS_FIELD_NUMBER: builtins.int
    PROCESS_EXECUTION_DIRECTORY_FIELD_NUMBER: builtins.int
    PROCESS_LOGS_PATH_FIELD_NUMBER: builtins.int
    process_execution_directory: builtins.str
    process_logs_path: builtins.str
    """map<string,string> runtime_environment = 4;"""
    @property
    def metadata(self) -> Global___ProcessMetadata: ...
    @property
    def env(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def executable_and_arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ProcessDescription.ExecAndArgs]: ...
    def __init__(
        self,
        *,
        metadata: Global___ProcessMetadata | None = ...,
        env: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        executable_and_arguments: collections.abc.Iterable[Global___ProcessDescription.ExecAndArgs] | None = ...,
        process_execution_directory: builtins.str = ...,
        process_logs_path: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["env", b"env", "executable_and_arguments", b"executable_and_arguments", "metadata", b"metadata", "process_execution_directory", b"process_execution_directory", "process_logs_path", b"process_logs_path"]) -> None: ...

Global___ProcessDescription: typing_extensions.TypeAlias = ProcessDescription

@typing.final
class ProcessInstance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StatusCode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProcessInstance._StatusCode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        RUNNING: ProcessInstance._StatusCode.ValueType  # 0
        DEAD: ProcessInstance._StatusCode.ValueType  # 1

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    RUNNING: ProcessInstance.StatusCode.ValueType  # 0
    DEAD: ProcessInstance.StatusCode.ValueType  # 1

    PROCESS_DESCRIPTION_FIELD_NUMBER: builtins.int
    PROCESS_RESTRICTION_FIELD_NUMBER: builtins.int
    STATUS_CODE_FIELD_NUMBER: builtins.int
    RETURN_CODE_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    status_code: Global___ProcessInstance.StatusCode.ValueType
    return_code: builtins.int
    @property
    def process_description(self) -> Global___ProcessDescription: ...
    @property
    def process_restriction(self) -> Global___ProcessRestriction: ...
    @property
    def uuid(self) -> Global___ProcessUUID: ...
    def __init__(
        self,
        *,
        process_description: Global___ProcessDescription | None = ...,
        process_restriction: Global___ProcessRestriction | None = ...,
        status_code: Global___ProcessInstance.StatusCode.ValueType = ...,
        return_code: builtins.int = ...,
        uuid: Global___ProcessUUID | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "uuid", b"uuid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "return_code", b"return_code", "status_code", b"status_code", "uuid", b"uuid"]) -> None: ...

Global___ProcessInstance: typing_extensions.TypeAlias = ProcessInstance

@typing.final
class ProcessInstanceList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ProcessInstance]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        token: druncschema.token_pb2.Token | None = ...,
        values: collections.abc.Iterable[Global___ProcessInstance] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["flag", b"flag", "name", b"name", "token", b"token", "values", b"values"]) -> None: ...

Global___ProcessInstanceList: typing_extensions.TypeAlias = ProcessInstanceList

@typing.final
class BootRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    PROCESS_DESCRIPTION_FIELD_NUMBER: builtins.int
    PROCESS_RESTRICTION_FIELD_NUMBER: builtins.int
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    @property
    def process_description(self) -> Global___ProcessDescription: ...
    @property
    def process_restriction(self) -> Global___ProcessRestriction: ...
    def __init__(
        self,
        *,
        token: druncschema.token_pb2.Token | None = ...,
        process_description: Global___ProcessDescription | None = ...,
        process_restriction: Global___ProcessRestriction | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["process_description", b"process_description", "process_restriction", b"process_restriction", "token", b"token"]) -> None: ...

Global___BootRequest: typing_extensions.TypeAlias = BootRequest
