"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from druncschema import token_pb2 as _token_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeploySessionResponseFlag(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Flag:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeploySessionResponseFlag._Flag.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SUCCESS: DeploySessionResponseFlag._Flag.ValueType  # 0
        FAILURE_CONFIGURATION_FILE_NOT_FOUND: DeploySessionResponseFlag._Flag.ValueType  # 1
        FAILURE_SESSION_ID_NOT_FOUND: DeploySessionResponseFlag._Flag.ValueType  # 2
        FAILURE_SESSION_NAME_IN_USE: DeploySessionResponseFlag._Flag.ValueType  # 3
        FAILURE_SESSION_NAME_INVALID: DeploySessionResponseFlag._Flag.ValueType  # 4
        FAILURE_RESOURCES_CANNOT_BE_ALLOCATED: DeploySessionResponseFlag._Flag.ValueType  # 5
        FAILURE_INSUFFICIENT_PRIVILEGES_TO_USE_RESOURCES: DeploySessionResponseFlag._Flag.ValueType  # 6
        FAILURE_WEB_PROXY_ENABLED: DeploySessionResponseFlag._Flag.ValueType  # 7
        FAILURE_OTHER: DeploySessionResponseFlag._Flag.ValueType  # 8

    class Flag(_Flag, metaclass=_FlagEnumTypeWrapper): ...
    SUCCESS: DeploySessionResponseFlag.Flag.ValueType  # 0
    FAILURE_CONFIGURATION_FILE_NOT_FOUND: DeploySessionResponseFlag.Flag.ValueType  # 1
    FAILURE_SESSION_ID_NOT_FOUND: DeploySessionResponseFlag.Flag.ValueType  # 2
    FAILURE_SESSION_NAME_IN_USE: DeploySessionResponseFlag.Flag.ValueType  # 3
    FAILURE_SESSION_NAME_INVALID: DeploySessionResponseFlag.Flag.ValueType  # 4
    FAILURE_RESOURCES_CANNOT_BE_ALLOCATED: DeploySessionResponseFlag.Flag.ValueType  # 5
    FAILURE_INSUFFICIENT_PRIVILEGES_TO_USE_RESOURCES: DeploySessionResponseFlag.Flag.ValueType  # 6
    FAILURE_WEB_PROXY_ENABLED: DeploySessionResponseFlag.Flag.ValueType  # 7
    FAILURE_OTHER: DeploySessionResponseFlag.Flag.ValueType  # 8

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___DeploySessionResponseFlag.Flag.ValueType
    def __init__(
        self,
        *,
        status: Global___DeploySessionResponseFlag.Flag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeploySessionResponseFlag: _TypeAlias = DeploySessionResponseFlag  # noqa: Y015

@_typing.final
class EndSessionResponseFlag(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Flag:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EndSessionResponseFlag._Flag.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SUCCESS: EndSessionResponseFlag._Flag.ValueType  # 0
        FAILURE_APPLICATION_STILL_ALIVE: EndSessionResponseFlag._Flag.ValueType  # 1
        FAILURE_OTHER: EndSessionResponseFlag._Flag.ValueType  # 2

    class Flag(_Flag, metaclass=_FlagEnumTypeWrapper): ...
    SUCCESS: EndSessionResponseFlag.Flag.ValueType  # 0
    FAILURE_APPLICATION_STILL_ALIVE: EndSessionResponseFlag.Flag.ValueType  # 1
    FAILURE_OTHER: EndSessionResponseFlag.Flag.ValueType  # 2

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___EndSessionResponseFlag.Flag.ValueType
    def __init__(
        self,
        *,
        status: Global___EndSessionResponseFlag.Flag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionResponseFlag: _TypeAlias = EndSessionResponseFlag  # noqa: Y015

@_typing.final
class ValidateSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_MANAGER_FIELD_NUMBER: _builtins.int
    PATH_TO_CONFIGURATION_FILE_FIELD_NUMBER: _builtins.int
    SSESION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NAME_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    process_manager: _builtins.str
    path_to_configuration_file: _builtins.str
    ssesion_id: _builtins.str
    session_name: _builtins.str
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        process_manager: _builtins.str = ...,
        path_to_configuration_file: _builtins.str = ...,
        ssesion_id: _builtins.str = ...,
        session_name: _builtins.str = ...,
        options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "path_to_configuration_file", b"path_to_configuration_file", "process_manager", b"process_manager", "session_name", b"session_name", "ssesion_id", b"ssesion_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateSessionRequest: _TypeAlias = ValidateSessionRequest  # noqa: Y015

@_typing.final
class ValidateSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def result(self) -> Global___DeploySessionResponseFlag: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        result: Global___DeploySessionResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateSessionResponse: _TypeAlias = ValidateSessionResponse  # noqa: Y015

@_typing.final
class StartSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_MANAGER_FIELD_NUMBER: _builtins.int
    PATH_TO_CONFIGURATION_FILE_FIELD_NUMBER: _builtins.int
    SSESION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NAME_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    process_manager: _builtins.str
    path_to_configuration_file: _builtins.str
    ssesion_id: _builtins.str
    session_name: _builtins.str
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        process_manager: _builtins.str = ...,
        path_to_configuration_file: _builtins.str = ...,
        ssesion_id: _builtins.str = ...,
        session_name: _builtins.str = ...,
        options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "path_to_configuration_file", b"path_to_configuration_file", "process_manager", b"process_manager", "session_name", b"session_name", "ssesion_id", b"ssesion_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartSessionRequest: _TypeAlias = StartSessionRequest  # noqa: Y015

@_typing.final
class StartSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def result(self) -> Global___DeploySessionResponseFlag: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        result: Global___DeploySessionResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartSessionResponse: _TypeAlias = StartSessionResponse  # noqa: Y015

@_typing.final
class EndSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_MANAGER_FIELD_NUMBER: _builtins.int
    PATH_TO_CONFIGURATION_FILE_FIELD_NUMBER: _builtins.int
    SSESION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NAME_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    process_manager: _builtins.str
    path_to_configuration_file: _builtins.str
    ssesion_id: _builtins.str
    session_name: _builtins.str
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        process_manager: _builtins.str = ...,
        path_to_configuration_file: _builtins.str = ...,
        ssesion_id: _builtins.str = ...,
        session_name: _builtins.str = ...,
        options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "path_to_configuration_file", b"path_to_configuration_file", "process_manager", b"process_manager", "session_name", b"session_name", "ssesion_id", b"ssesion_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionRequest: _TypeAlias = EndSessionRequest  # noqa: Y015

@_typing.final
class EndSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def result(self) -> Global___EndSessionResponseFlag: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        result: Global___EndSessionResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionResponse: _TypeAlias = EndSessionResponse  # noqa: Y015
