"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from druncschema import generic_pb2 as _generic_pb2
from druncschema import request_response_pb2 as _request_response_pb2
from druncschema import token_pb2 as _token_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DeploySessionResponseFlag(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Flag:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeploySessionResponseFlag._Flag.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SUCCESS: DeploySessionResponseFlag._Flag.ValueType  # 0
        FAILURE_CONFIGURATION_FILE_NOT_FOUND: DeploySessionResponseFlag._Flag.ValueType  # 1
        FAILURE_SESSION_ID_NOT_FOUND: DeploySessionResponseFlag._Flag.ValueType  # 2
        FAILURE_SESSION_NAME_IN_USE: DeploySessionResponseFlag._Flag.ValueType  # 3
        FAILURE_SESSION_NAME_INVALID: DeploySessionResponseFlag._Flag.ValueType  # 4
        FAILURE_RESOURCES_CANNOT_BE_ALLOCATED: DeploySessionResponseFlag._Flag.ValueType  # 5
        FAILURE_INSUFFICIENT_PRIVILEGES_TO_USE_RESOURCES: DeploySessionResponseFlag._Flag.ValueType  # 6
        FAILURE_WEB_PROXY_ENABLED: DeploySessionResponseFlag._Flag.ValueType  # 7
        FAILURE_OTHER: DeploySessionResponseFlag._Flag.ValueType  # 8

    class Flag(_Flag, metaclass=_FlagEnumTypeWrapper): ...
    SUCCESS: DeploySessionResponseFlag.Flag.ValueType  # 0
    FAILURE_CONFIGURATION_FILE_NOT_FOUND: DeploySessionResponseFlag.Flag.ValueType  # 1
    FAILURE_SESSION_ID_NOT_FOUND: DeploySessionResponseFlag.Flag.ValueType  # 2
    FAILURE_SESSION_NAME_IN_USE: DeploySessionResponseFlag.Flag.ValueType  # 3
    FAILURE_SESSION_NAME_INVALID: DeploySessionResponseFlag.Flag.ValueType  # 4
    FAILURE_RESOURCES_CANNOT_BE_ALLOCATED: DeploySessionResponseFlag.Flag.ValueType  # 5
    FAILURE_INSUFFICIENT_PRIVILEGES_TO_USE_RESOURCES: DeploySessionResponseFlag.Flag.ValueType  # 6
    FAILURE_WEB_PROXY_ENABLED: DeploySessionResponseFlag.Flag.ValueType  # 7
    FAILURE_OTHER: DeploySessionResponseFlag.Flag.ValueType  # 8

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___DeploySessionResponseFlag.Flag.ValueType
    def __init__(
        self,
        *,
        status: Global___DeploySessionResponseFlag.Flag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeploySessionResponseFlag: _TypeAlias = DeploySessionResponseFlag  # noqa: Y015

@_typing.final
class EndSessionResponseFlag(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Flag:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _FlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EndSessionResponseFlag._Flag.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SUCCESS: EndSessionResponseFlag._Flag.ValueType  # 0
        FAILURE_APPLICATION_STILL_ALIVE: EndSessionResponseFlag._Flag.ValueType  # 1
        FAILURE_OTHER: EndSessionResponseFlag._Flag.ValueType  # 2

    class Flag(_Flag, metaclass=_FlagEnumTypeWrapper): ...
    SUCCESS: EndSessionResponseFlag.Flag.ValueType  # 0
    FAILURE_APPLICATION_STILL_ALIVE: EndSessionResponseFlag.Flag.ValueType  # 1
    FAILURE_OTHER: EndSessionResponseFlag.Flag.ValueType  # 2

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___EndSessionResponseFlag.Flag.ValueType
    def __init__(
        self,
        *,
        status: Global___EndSessionResponseFlag.Flag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionResponseFlag: _TypeAlias = EndSessionResponseFlag  # noqa: Y015

@_typing.final
class ValidateSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_MANAGER_FIELD_NUMBER: _builtins.int
    PATH_TO_CONFIGURATION_FILE_FIELD_NUMBER: _builtins.int
    SSESION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NAME_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    process_manager: _builtins.str
    path_to_configuration_file: _builtins.str
    ssesion_id: _builtins.str
    session_name: _builtins.str
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        process_manager: _builtins.str = ...,
        path_to_configuration_file: _builtins.str = ...,
        ssesion_id: _builtins.str = ...,
        session_name: _builtins.str = ...,
        options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "path_to_configuration_file", b"path_to_configuration_file", "process_manager", b"process_manager", "session_name", b"session_name", "ssesion_id", b"ssesion_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateSessionRequest: _TypeAlias = ValidateSessionRequest  # noqa: Y015

@_typing.final
class ValidateSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def result(self) -> Global___DeploySessionResponseFlag: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        result: Global___DeploySessionResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateSessionResponse: _TypeAlias = ValidateSessionResponse  # noqa: Y015

@_typing.final
class StartSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_MANAGER_FIELD_NUMBER: _builtins.int
    PATH_TO_CONFIGURATION_FILE_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NAME_FIELD_NUMBER: _builtins.int
    OVERRIDE_LOGS_FIELD_NUMBER: _builtins.int
    CONTROLLER_LOG_LEVEL_FIELD_NUMBER: _builtins.int
    SLEEP_BETWEEN_APP_BOOT_FIELD_NUMBER: _builtins.int
    process_manager: _builtins.str
    path_to_configuration_file: _builtins.str
    session_id: _builtins.str
    session_name: _builtins.str
    override_logs: _builtins.bool
    controller_log_level: _builtins.str
    sleep_between_app_boot: _builtins.float
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        process_manager: _builtins.str = ...,
        path_to_configuration_file: _builtins.str = ...,
        session_id: _builtins.str = ...,
        session_name: _builtins.str = ...,
        override_logs: _builtins.bool = ...,
        controller_log_level: _builtins.str = ...,
        sleep_between_app_boot: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["controller_log_level", b"controller_log_level", "override_logs", b"override_logs", "path_to_configuration_file", b"path_to_configuration_file", "process_manager", b"process_manager", "session_id", b"session_id", "session_name", b"session_name", "sleep_between_app_boot", b"sleep_between_app_boot", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartSessionRequest: _TypeAlias = StartSessionRequest  # noqa: Y015

@_typing.final
class StartSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def result(self) -> Global___DeploySessionResponseFlag: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        result: Global___DeploySessionResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartSessionResponse: _TypeAlias = StartSessionResponse  # noqa: Y015

@_typing.final
class EndSessionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OptionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TOKEN_FIELD_NUMBER: _builtins.int
    PROCESS_MANAGER_FIELD_NUMBER: _builtins.int
    PATH_TO_CONFIGURATION_FILE_FIELD_NUMBER: _builtins.int
    SSESION_ID_FIELD_NUMBER: _builtins.int
    SESSION_NAME_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    process_manager: _builtins.str
    path_to_configuration_file: _builtins.str
    ssesion_id: _builtins.str
    session_name: _builtins.str
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def options(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        process_manager: _builtins.str = ...,
        path_to_configuration_file: _builtins.str = ...,
        ssesion_id: _builtins.str = ...,
        session_name: _builtins.str = ...,
        options: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["options", b"options", "path_to_configuration_file", b"path_to_configuration_file", "process_manager", b"process_manager", "session_name", b"session_name", "ssesion_id", b"ssesion_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionRequest: _TypeAlias = EndSessionRequest  # noqa: Y015

@_typing.final
class EndSessionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def result(self) -> Global___EndSessionResponseFlag: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        result: Global___EndSessionResponseFlag | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EndSessionResponse: _TypeAlias = EndSessionResponse  # noqa: Y015

@_typing.final
class ValidateCommunicationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateCommunicationRequest: _TypeAlias = ValidateCommunicationRequest  # noqa: Y015

@_typing.final
class ValidateCommunicationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    status: _generic_pb2.OutcomeFlag.ValueType
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        status: _generic_pb2.OutcomeFlag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateCommunicationResponse: _TypeAlias = ValidateCommunicationResponse  # noqa: Y015

@_typing.final
class LogOnServerRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    EXECUTE_ALONG_PATH_FIELD_NUMBER: _builtins.int
    EXECUTE_ON_ALL_SUBSEQUENT_CHILDREN_IN_PATH_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    severity: _builtins.str
    target: _builtins.str
    execute_along_path: _builtins.bool
    execute_on_all_subsequent_children_in_path: _builtins.bool
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        text: _builtins.str = ...,
        severity: _builtins.str = ...,
        target: _builtins.str = ...,
        execute_along_path: _builtins.bool = ...,
        execute_on_all_subsequent_children_in_path: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["execute_along_path", b"execute_along_path", "execute_on_all_subsequent_children_in_path", b"execute_on_all_subsequent_children_in_path", "severity", b"severity", "target", b"target", "text", b"text", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LogOnServerRequest: _TypeAlias = LogOnServerRequest  # noqa: Y015

@_typing.final
class LogOnServerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOKEN_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    FLAG_FIELD_NUMBER: _builtins.int
    CHILDREN_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    flag: _request_response_pb2.ResponseFlag.ValueType
    @_builtins.property
    def token(self) -> _token_pb2.Token: ...
    @_builtins.property
    def children(self) -> _containers.RepeatedCompositeFieldContainer[Global___LogOnServerResponse]: ...
    def __init__(
        self,
        *,
        token: _token_pb2.Token | None = ...,
        name: _builtins.str = ...,
        flag: _request_response_pb2.ResponseFlag.ValueType = ...,
        children: _abc.Iterable[Global___LogOnServerResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["token", b"token"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["children", b"children", "flag", b"flag", "name", b"name", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LogOnServerResponse: _TypeAlias = LogOnServerResponse  # noqa: Y015
