# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from druncschema import common_pb2 as druncschema_dot_common__pb2
from druncschema import description_pb2 as druncschema_dot_description__pb2
from druncschema import request_response_pb2 as druncschema_dot_request__response__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in druncschema/run_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_log = channel.unary_unary(
                '/dunedaq.druncschema.run_control.RunControl/send_log',
                request_serializer=druncschema_dot_common__pb2.SendLogRequest.SerializeToString,
                response_deserializer=druncschema_dot_common__pb2.SendLogResponse.FromString,
                _registered_method=True)
        self.describe = channel.unary_unary(
                '/dunedaq.druncschema.run_control.RunControl/describe',
                request_serializer=druncschema_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncschema_dot_description__pb2.Description.FromString,
                _registered_method=True)


class RunControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_log': grpc.unary_unary_rpc_method_handler(
                    servicer.send_log,
                    request_deserializer=druncschema_dot_common__pb2.SendLogRequest.FromString,
                    response_serializer=druncschema_dot_common__pb2.SendLogResponse.SerializeToString,
            ),
            'describe': grpc.unary_unary_rpc_method_handler(
                    servicer.describe,
                    request_deserializer=druncschema_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncschema_dot_description__pb2.Description.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dunedaq.druncschema.run_control.RunControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dunedaq.druncschema.run_control.RunControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncschema.run_control.RunControl/send_log',
            druncschema_dot_common__pb2.SendLogRequest.SerializeToString,
            druncschema_dot_common__pb2.SendLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncschema.run_control.RunControl/describe',
            druncschema_dot_request__response__pb2.Request.SerializeToString,
            druncschema_dot_description__pb2.Description.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
