"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from druncschema import description_pb2 as _description_pb2
from druncschema import request_response_pb2 as _request_response_pb2
from druncschema import session_manager_pb2 as _session_manager_pb2
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SessionManagerStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SessionManagerAsyncStub: ...
    describe: _grpc.UnaryUnaryMultiCallable[_request_response_pb2.Request, _description_pb2.Description]
    list_all_sessions: _grpc.UnaryUnaryMultiCallable[_request_response_pb2.Request, _session_manager_pb2.AllActiveSessions]
    list_all_configs: _grpc.UnaryUnaryMultiCallable[_request_response_pb2.Request, _session_manager_pb2.AllConfigKeys]

@_typing.type_check_only
class SessionManagerAsyncStub(SessionManagerStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    describe: _aio.UnaryUnaryMultiCallable[_request_response_pb2.Request, _description_pb2.Description]  # type: ignore[assignment]
    list_all_sessions: _aio.UnaryUnaryMultiCallable[_request_response_pb2.Request, _session_manager_pb2.AllActiveSessions]  # type: ignore[assignment]
    list_all_configs: _aio.UnaryUnaryMultiCallable[_request_response_pb2.Request, _session_manager_pb2.AllConfigKeys]  # type: ignore[assignment]

class SessionManagerServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def describe(
        self,
        request: _request_response_pb2.Request,
        context: _ServicerContext,
    ) -> _typing.Union[_description_pb2.Description, _abc.Awaitable[_description_pb2.Description]]: ...

    @_abc_1.abstractmethod
    def list_all_sessions(
        self,
        request: _request_response_pb2.Request,
        context: _ServicerContext,
    ) -> _typing.Union[_session_manager_pb2.AllActiveSessions, _abc.Awaitable[_session_manager_pb2.AllActiveSessions]]: ...

    @_abc_1.abstractmethod
    def list_all_configs(
        self,
        request: _request_response_pb2.Request,
        context: _ServicerContext,
    ) -> _typing.Union[_session_manager_pb2.AllConfigKeys, _abc.Awaitable[_session_manager_pb2.AllConfigKeys]]: ...

def add_SessionManagerServicer_to_server(servicer: SessionManagerServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
