syntax = "proto3";

package dunedaq.druncschema;

import "druncschema/generic.proto";
import "druncschema/token.proto";
import "druncschema/request_response.proto";

message LogOnServerRequest {
  Token token = 1;
  string text = 2;
  string severity = 3;
  string target = 4;
  bool execute_along_path = 5;
  bool execute_on_all_subsequent_children_in_path = 6;
}

message LogOnServerResponse {
  Token token = 1;
  string name = 2;
  ResponseFlag flag = 3;
  repeated LogOnServerResponse children = 4;
}