syntax = "proto3";

package dunedaq.druncschema.controller;

import "druncschema/request_response.proto";
import "druncschema/description.proto";
import "druncschema/token.proto";
import "google/protobuf/any.proto";

service Controller {
  rpc describe                   (DescribeRequest) returns (DescribeResponse) {}
  rpc status                     (StatusRequest) returns (StatusResponse) {}

  rpc describe_fsm               (DescribeFSMRequest) returns (DescribeFSMResponse) {}
  rpc execute_fsm_command        (ExecuteFSMCommandRequest) returns (ExecuteFSMCommandResponse) {}
  rpc execute_expert_command     (ExecuteExpertCommandRequest) returns (ExecuteExpertCommandResponse) {}
  rpc include                    (IncludeRequest) returns (IncludeResponse) {}
  rpc exclude                    (ExcludeRequest) returns (ExcludeResponse) {}
  rpc recompute_status           (RecomputeStatusRequest) returns (RecomputeStatusResponse) {}

  rpc take_control               (Request) returns (Response) {}
  rpc surrender_control          (Request) returns (Response) {}
  rpc who_is_in_charge           (Request) returns (Response) {}

  rpc to_error                   (Request) returns (Response) {}
}

message AddressedCommand {
  Token token = 1;
  string command_name = 2;
  optional google.protobuf.Any command_data = 3;
  string target = 4;
  bool execute_along_path = 5;
  bool execute_on_all_subsequent_children_in_path = 6;
}

message ExecuteExpertCommandRequest {
  Token token = 1;
  string json_string = 2;
  string target = 3;
  bool execute_along_path = 4;
  bool execute_on_all_subsequent_children_in_path = 5;
}

message ExecuteExpertCommandResponse {
  Token token = 1;
  string name = 2;
  string data = 4;
  repeated ExecuteExpertCommandResponse children = 5;
  FSMResponseFlag fsm_flag = 6;
  ResponseFlag flag = 7;
}

message ExecuteFSMCommandRequest {
  Token token = 1;
  FSMCommand command = 2;
  string target = 3;
  bool execute_along_path = 4;
  bool execute_on_all_subsequent_children_in_path = 5;
}

message ExecuteFSMCommandResponse {
  Token token = 1;
  string name = 2;
  string command_name = 3;
  string data = 4;
  repeated ExecuteFSMCommandResponse children = 5;
  FSMResponseFlag fsm_flag = 6;
  ResponseFlag flag = 7;
}

message FSMCommand {
  string command_name = 1;
  map<string, google.protobuf.Any> arguments = 2;
  optional string data = 4;
}

message IncludeRequest {
  Token token = 1;
  string target = 2;
  bool execute_along_path = 3;
  bool execute_on_all_subsequent_children_in_path = 4;
}

message IncludeResponse {
  Token token = 1;
  string name = 2;
  string text = 3;
  repeated IncludeResponse children = 4;
  ResponseFlag flag = 5;
}

message ExcludeRequest {
  Token token = 1;
  string target = 2;
  bool execute_along_path = 3;
  bool execute_on_all_subsequent_children_in_path = 4;
}

message ExcludeResponse {
  Token token = 1;
  string name = 2;
  string text = 3;
  repeated ExcludeResponse children = 4;
  ResponseFlag flag = 5;
}

message StatusRequest {
  Token token = 1;
  string target = 2;
  bool execute_along_path = 3;
  bool execute_on_all_subsequent_children_in_path = 4;
}

message StatusResponse {
  Token token = 1;
  string name = 2;
  Status status = 3;
  repeated StatusResponse children = 4;
  ResponseFlag flag = 5;
}

message RecomputeStatusRequest {
  Token token = 1;
  string target = 2;
  bool execute_along_path = 3;
  bool execute_on_all_subsequent_children_in_path = 4;
}

message RecomputeStatusResponse {
  Token token = 1;
  string name = 2;
  repeated RecomputeStatusResponse children = 3;
  ResponseFlag flag = 4;
}

message DescribeRequest {
  Token token = 1;
  string target = 2;
  bool execute_along_path = 3;
  bool execute_on_all_subsequent_children_in_path = 4;
}

message DescribeResponse {
  Token token = 1;
  string name = 2;
  Description description = 3;
  repeated DescribeResponse children = 4;
  ResponseFlag flag = 5;
}

message DescribeFSMRequest {
  Token token = 1;
  string key = 2;
  string target = 3;
  bool execute_along_path = 4;
  bool execute_on_all_subsequent_children_in_path = 5;
}

message DescribeFSMResponse {
  Token token = 1;
  string name = 2;
  FSMCommandsDescription description = 3;
  repeated DescribeFSMResponse children = 4;
  ResponseFlag flag = 5;
}

enum FSMResponseFlag {
  FSM_EXECUTED_SUCCESSFULLY = 0;
  FSM_FAILED = 1;
  FSM_INVALID_TRANSITION = 2;
  FSM_NOT_EXECUTED_EXCLUDED = 3;
  FSM_NOT_EXECUTED_IN_ERROR = 4;
}

message Argument {
  enum Presence {
    MANDATORY = 0;
    OPTIONAL = 1;
  }
  enum Type {
    INT = 0;
    FLOAT = 1;
    STRING = 2;
    BOOL = 3;
  }
  string name = 1;
  Presence presence = 2;
  Type type = 3;
  optional google.protobuf.Any default_value = 4;
  repeated google.protobuf.Any choices = 5;
  string help = 6;
}

message FSMCommandDescription {
  string name = 1;
  repeated string data_type = 2;
  string help = 3;
  string return_type = 4;
  repeated Argument arguments = 5;
}

message FSMSequence {
  string id = 1;
  repeated string command_ids = 2;
}

message FSMCommandsDescription {
  Token token = 1;
  string type = 2;
  string name = 3;
  optional string session = 4;
  repeated FSMCommandDescription commands = 5;
  repeated FSMSequence sequences = 6;
}

message Status {
  string state = 2;
  string sub_state = 3;
  bool in_error = 4;
  bool included = 5;
  optional RunInfo run_info = 6;
}

message RunInfo {
  string run_type = 1;
  double trigger_rate = 2;
  uint64  run_number = 3;
  bool disable_data_storage = 4;
  uint32 run_time_at_start = 5;
  uint32 run_time_since_start = 6;
  string run_config_file = 7;
  string run_config_name = 8;
}
