syntax = "proto3";

package dunedaq.druncschema.process_manager;

import "druncschema/request_response.proto";
import "druncschema/description.proto";
import "druncschema/token.proto";

service ProcessManager {
  rpc describe  (Request) returns (Description) {}
  rpc boot      (BootRequest) returns (ProcessInstanceList) {}
  rpc terminate (Request) returns (ProcessInstanceList) {}
  rpc restart   (ProcessQuery) returns (ProcessInstanceList) {}
  rpc kill      (ProcessQuery) returns (ProcessInstanceList) {}
  rpc flush     (ProcessQuery) returns (ProcessInstanceList) {}
  rpc ps        (ProcessQuery) returns (ProcessInstanceList) {}
  rpc logs      (LogRequest) returns (LogLines) {}
}

message ProcessRestriction {
  repeated string allowed_hosts = 1;
  repeated string allowed_host_types = 2;
}

message CommandNotificationMessage {
  string user = 1;
  string command = 2;
}

message GenericNotificationMessage {
  string message = 1;
}

message ExceptionNotification {
  message StackLine {
    string line_text = 1;
    string line_number = 2;
    string file = 3;
  };
  string error_text = 1;
  repeated StackLine stack_trace = 2;
}

message LogRequest {
  Token token = 1;
  ProcessQuery query = 2;
  int32 how_far = 3;
}

message LogLines {
  string name = 1;
  Token token = 2;
  ProcessUUID uuid = 3;
  repeated string lines = 4;
  ResponseFlag flag = 5;
}

message ProcessUUID {
  string uuid = 1;
}

message ProcessMetadata {
  ProcessUUID uuid = 1;
  string user = 2;
  optional string session = 3;
  string name = 4;
  string hostname = 5;
  optional string tree_id = 6;
}

message ProcessQuery {
  Token token = 1;
  repeated ProcessUUID uuids = 2;
  repeated string names = 3;
  string user = 4;
  string session = 5;
}

message ProcessDescription {
  message StringList {
    repeated string values = 1;
  };
  message ExecAndArgs{
    string exec = 1;
    repeated string args = 2;
  };
  ProcessMetadata metadata = 1;
  map<string,string> env = 2;
  repeated ExecAndArgs executable_and_arguments = 3;
  string process_execution_directory = 4;
  string process_logs_path = 5;
  // map<string,string> runtime_environment = 4;
}

message ProcessInstance {
  ProcessDescription process_description = 1;
  ProcessRestriction process_restriction = 2;
  enum StatusCode {
    RUNNING = 0;
    DEAD = 1;
  };
  StatusCode status_code = 3;
  int32 return_code = 4;
  ProcessUUID uuid = 5;
}

message ProcessInstanceList {
  string name = 1;
  Token token = 2;
  repeated ProcessInstance values = 3;
  ResponseFlag flag = 4;
}

message BootRequest {
  Token token = 1;
  ProcessDescription process_description = 2;
  ProcessRestriction process_restriction = 3;
}
