syntax = "proto3";

package dunedaq.druncschema;

import "druncschema/request_response.proto";
import "druncschema/description.proto";
import "druncschema/token.proto";
import "google/protobuf/empty.proto";

service SessionManager {
  rpc describe          (google.protobuf.Empty) returns (Description) {}
  rpc list_all_sessions (google.protobuf.Empty) returns (AllActiveSessions) {}
  rpc list_all_configs  (google.protobuf.Empty) returns (AllConfigKeys) {}
}

message ConfigKey {
  string file = 1;
  string session_id = 2;
}

message AllConfigKeys {
  string name = 1;
  Token token = 2;
  repeated ConfigKey config_keys = 3;
  ResponseFlag flag = 4;
}

message ActiveSession {
  string name = 1;
  string user = 2;
  ConfigKey config_key = 3;
}

message AllActiveSessions {
  string name = 1;
  Token token = 2;
  repeated ActiveSession active_sessions = 3;
  ResponseFlag flag = 4;
}
