# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drunc_messages/request_response.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'drunc_messages/request_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from drunc_messages import token_pb2 as drunc_messages_dot_token__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"drunc_messages/request_response.proto\x12\x13\x64unedaq.drunc_messages\x1a\x17\x64runcschema/token.proto\x1a\x19google/protobuf/any.proto\"f\n\x07Request\x12)\n\x05token\x18\x01 \x01(\x0b\x32\x1a.dunedaq.drunc_messages.Token\x12\'\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x42\x07\n\x05_data\"\xd7\x01\n\x08Response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x05token\x18\x02 \x01(\x0b\x32\x1a.dunedaq.drunc_messages.Token\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x88\x01\x01\x12/\n\x04\x66lag\x18\x04 \x01(\x0e\x32!.dunedaq.drunc_messages.ResponseFlag\x12/\n\x08\x63hildren\x18\x05 \x03(\x0b\x32\x1d.dunedaq.drunc_messages.ResponseB\x07\n\x05_data\"X\n\x12\x43ommandDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x03(\t\x12\x0c\n\x04help\x18\x03 \x01(\t\x12\x13\n\x0breturn_type\x18\x04 \x01(\t\"\xf0\x01\n\x0b\x44\x65scription\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x11\n\x04info\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07session\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x39\n\x08\x63ommands\x18\x06 \x03(\x0b\x32\'.dunedaq.drunc_messages.CommandDescription\x12,\n\tbroadcast\x18\x07 \x01(\x0b\x32\x14.google.protobuf.AnyH\x02\x88\x01\x01\x42\x07\n\x05_infoB\n\n\x08_sessionB\x0c\n\n_broadcast*\x9a\x02\n\x0cResponseFlag\x12\x19\n\x15\x45XECUTED_SUCCESSFULLY\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12 \n\x1cNOT_EXECUTED_NOT_IMPLEMENTED\x10\x02\x12\x1f\n\x1bNOT_EXECUTED_NOT_IN_CONTROL\x10\x03\x12\x1f\n\x1bNOT_EXECUTED_NOT_AUTHORISED\x10\x04\x12\x1e\n\x1aNOT_EXECUTED_NODE_IN_ERROR\x10\x05\x12\x1a\n\x16\x44RUNC_EXCEPTION_THROWN\x10\x06\x12\x1e\n\x1aUNHANDLED_EXCEPTION_THROWN\x10\x07\x12#\n\x1fNOT_EXECUTED_BAD_REQUEST_FORMAT\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drunc_messages.request_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEFLAG']._serialized_start=767
  _globals['_RESPONSEFLAG']._serialized_end=1049
  _globals['_REQUEST']._serialized_start=111
  _globals['_REQUEST']._serialized_end=213
  _globals['_RESPONSE']._serialized_start=216
  _globals['_RESPONSE']._serialized_end=431
  _globals['_COMMANDDESCRIPTION']._serialized_start=433
  _globals['_COMMANDDESCRIPTION']._serialized_end=521
  _globals['_DESCRIPTION']._serialized_start=524
  _globals['_DESCRIPTION']._serialized_end=764
# @@protoc_insertion_point(module_scope)
