# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drunc_messages/session_manager.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'drunc_messages/session_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from drunc_messages import request_response_pb2 as drunc__messages_dot_request__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$drunc_messages/session_manager.proto\x12\x16\x64unedaq.drunc_messages\x1a%drunc_messages/request_response.proto\"-\n\tConfigKey\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"G\n\rAllConfigKeys\x12\x36\n\x0b\x63onfig_keys\x18\x01 \x03(\x0b\x32!.dunedaq.drunc_messages.ConfigKey\"b\n\rActiveSession\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x35\n\nconfig_key\x18\x03 \x01(\x0b\x32!.dunedaq.drunc_messages.ConfigKey\"S\n\x11\x41llActiveSessions\x12>\n\x0f\x61\x63tive_sessions\x18\x01 \x03(\x0b\x32%.dunedaq.drunc_messages.ActiveSession2\x93\x04\n\x0eSessionManager\x12O\n\x08\x64\x65scribe\x12\x1f.dunedaq.drunc_messages.Request\x1a .dunedaq.drunc_messages.Response\"\x00\x12X\n\x11list_all_sessions\x12\x1f.dunedaq.drunc_messages.Request\x1a .dunedaq.drunc_messages.Response\"\x00\x12T\n\rstart_session\x12\x1f.dunedaq.drunc_messages.Request\x1a .dunedaq.drunc_messages.Response\"\x00\x12S\n\x0cstop_session\x12\x1f.dunedaq.drunc_messages.Request\x1a .dunedaq.drunc_messages.Response\"\x00\x12W\n\x10list_all_configs\x12\x1f.dunedaq.drunc_messages.Request\x1a .dunedaq.drunc_messages.Response\"\x00\x12R\n\x0bload_config\x12\x1f.dunedaq.drunc_messages.Request\x1a .dunedaq.drunc_messages.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drunc_messages.session_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGKEY']._serialized_start=103
  _globals['_CONFIGKEY']._serialized_end=148
  _globals['_ALLCONFIGKEYS']._serialized_start=150
  _globals['_ALLCONFIGKEYS']._serialized_end=221
  _globals['_ACTIVESESSION']._serialized_start=223
  _globals['_ACTIVESESSION']._serialized_end=321
  _globals['_ALLACTIVESESSIONS']._serialized_start=323
  _globals['_ALLACTIVESESSIONS']._serialized_end=406
  _globals['_SESSIONMANAGER']._serialized_start=409
  _globals['_SESSIONMANAGER']._serialized_end=940
# @@protoc_insertion_point(module_scope)
