"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FSMStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    SUB_STATE_FIELD_NUMBER: _builtins.int
    IN_ERROR_FIELD_NUMBER: _builtins.int
    INCLUDED_FIELD_NUMBER: _builtins.int
    state: _builtins.str
    sub_state: _builtins.str
    in_error: _builtins.bool
    included: _builtins.bool
    def __init__(
        self,
        *,
        state: _builtins.str = ...,
        sub_state: _builtins.str = ...,
        in_error: _builtins.bool = ...,
        included: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["in_error", b"in_error", "included", b"included", "state", b"state", "sub_state", b"sub_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FSMStatus: _TypeAlias = FSMStatus  # noqa: Y015

@_typing.final
class CommandTime(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXECUTION_TIME_NS_FIELD_NUMBER: _builtins.int
    execution_time_ns: _builtins.int
    def __init__(
        self,
        *,
        execution_time_ns: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["execution_time_ns", b"execution_time_ns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommandTime: _TypeAlias = CommandTime  # noqa: Y015
