"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FSMStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    SUB_STATE_FIELD_NUMBER: builtins.int
    IN_ERROR_FIELD_NUMBER: builtins.int
    INCLUDED_FIELD_NUMBER: builtins.int
    state: builtins.str
    sub_state: builtins.str
    in_error: builtins.bool
    included: builtins.bool
    def __init__(
        self,
        *,
        state: builtins.str = ...,
        sub_state: builtins.str = ...,
        in_error: builtins.bool = ...,
        included: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["in_error", b"in_error", "included", b"included", "state", b"state", "sub_state", b"sub_state"]) -> None: ...

Global___FSMStatus: typing_extensions.TypeAlias = FSMStatus

@typing.final
class CommandTime(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_TIME_NS_FIELD_NUMBER: builtins.int
    execution_time_ns: builtins.int
    def __init__(
        self,
        *,
        execution_time_ns: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["execution_time_ns", b"execution_time_ns"]) -> None: ...

Global___CommandTime: typing_extensions.TypeAlias = CommandTime
