"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RunInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_TYPE_FIELD_NUMBER: _builtins.int
    TRIGGER_RATE_FIELD_NUMBER: _builtins.int
    RUN_NUMBER_FIELD_NUMBER: _builtins.int
    DISABLE_DATA_STORAGE_FIELD_NUMBER: _builtins.int
    RUN_TIME_AT_START_FIELD_NUMBER: _builtins.int
    RUN_TIME_SINCE_START_FIELD_NUMBER: _builtins.int
    RUN_CONFIG_FILE_FIELD_NUMBER: _builtins.int
    RUN_CONFIG_NAME_FIELD_NUMBER: _builtins.int
    run_type: _builtins.str
    trigger_rate: _builtins.float
    run_number: _builtins.int
    disable_data_storage: _builtins.bool
    run_time_at_start: _builtins.int
    run_time_since_start: _builtins.int
    run_config_file: _builtins.str
    run_config_name: _builtins.str
    def __init__(
        self,
        *,
        run_type: _builtins.str = ...,
        trigger_rate: _builtins.float = ...,
        run_number: _builtins.int = ...,
        disable_data_storage: _builtins.bool = ...,
        run_time_at_start: _builtins.int = ...,
        run_time_since_start: _builtins.int = ...,
        run_config_file: _builtins.str = ...,
        run_config_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["disable_data_storage", b"disable_data_storage", "run_config_file", b"run_config_file", "run_config_name", b"run_config_name", "run_number", b"run_number", "run_time_at_start", b"run_time_at_start", "run_time_since_start", b"run_time_since_start", "run_type", b"run_type", "trigger_rate", b"trigger_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RunInfo: _TypeAlias = RunInfo  # noqa: Y015
