"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ProcessStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    N_RUNNING_FIELD_NUMBER: _builtins.int
    N_DEAD_FIELD_NUMBER: _builtins.int
    N_SESSION_FIELD_NUMBER: _builtins.int
    n_running: _builtins.int
    n_dead: _builtins.int
    n_session: _builtins.int
    def __init__(
        self,
        *,
        n_running: _builtins.int = ...,
        n_dead: _builtins.int = ...,
        n_session: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["n_dead", b"n_dead", "n_running", b"n_running", "n_session", b"n_session"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProcessStatus: _TypeAlias = ProcessStatus  # noqa: Y015
