"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ProcessStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    N_RUNNING_FIELD_NUMBER: builtins.int
    N_DEAD_FIELD_NUMBER: builtins.int
    N_SESSION_FIELD_NUMBER: builtins.int
    n_running: builtins.int
    n_dead: builtins.int
    n_session: builtins.int
    def __init__(
        self,
        *,
        n_running: builtins.int = ...,
        n_dead: builtins.int = ...,
        n_session: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["n_dead", b"n_dead", "n_running", b"n_running", "n_session", b"n_session"]) -> None: ...

Global___ProcessStatus: typing_extensions.TypeAlias = ProcessStatus
