# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: druncmessages/authoriser.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'druncmessages/authoriser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from druncmessages import token_pb2 as druncmessages_dot_token__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64runcmessages/authoriser.proto\x12\x15\x64unedaq.druncmessages\x1a\x19\x64runcmessages/token.proto\"\xa6\x01\n\x11\x41uthoriserRequest\x12+\n\x05token\x18\x01 \x01(\x0b\x32\x1c.dunedaq.druncmessages.Token\x12\x31\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32!.dunedaq.druncmessages.ActionType\x12\x31\n\x06system\x18\x03 \x01(\x0e\x32!.dunedaq.druncmessages.SystemType*F\n\nActionType\x12\n\n\x06\x43REATE\x10\x00\x12\x08\n\x04READ\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x12\n\n\x06\x45XPERT\x10\x04*\x8a\x01\n\nSystemType\x12\x0e\n\nCONTROLLER\x10\x00\x12\x0f\n\x0b\x41PPLICATION\x10\x01\x12\x18\n\x14PROCESS_ORCHESTRATOR\x10\x02\x12\x13\n\x0fSESSION_MANAGER\x10\x03\x12\x14\n\x10RESOURCE_MANAGER\x10\x04\x12\x16\n\x12\x41UTHORISER_SERVICE\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'druncmessages.authoriser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONTYPE']._serialized_start=253
  _globals['_ACTIONTYPE']._serialized_end=323
  _globals['_SYSTEMTYPE']._serialized_start=326
  _globals['_SYSTEMTYPE']._serialized_end=464
  _globals['_AUTHORISERREQUEST']._serialized_start=85
  _globals['_AUTHORISERREQUEST']._serialized_end=251
# @@protoc_insertion_point(module_scope)
