"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import druncmessages.token_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ActionType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ActionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ActionType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CREATE: _ActionType.ValueType  # 0
    READ: _ActionType.ValueType  # 1
    UPDATE: _ActionType.ValueType  # 2
    DELETE: _ActionType.ValueType  # 3
    EXPERT: _ActionType.ValueType  # 4

class ActionType(_ActionType, metaclass=_ActionTypeEnumTypeWrapper): ...

CREATE: ActionType.ValueType  # 0
READ: ActionType.ValueType  # 1
UPDATE: ActionType.ValueType  # 2
DELETE: ActionType.ValueType  # 3
EXPERT: ActionType.ValueType  # 4
global___ActionType = ActionType

class _SystemType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SystemTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SystemType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONTROLLER: _SystemType.ValueType  # 0
    APPLICATION: _SystemType.ValueType  # 1
    PROCESS_ORCHESTRATOR: _SystemType.ValueType  # 2
    SESSION_MANAGER: _SystemType.ValueType  # 3
    RESOURCE_MANAGER: _SystemType.ValueType  # 4
    AUTHORISER_SERVICE: _SystemType.ValueType  # 5

class SystemType(_SystemType, metaclass=_SystemTypeEnumTypeWrapper): ...

CONTROLLER: SystemType.ValueType  # 0
APPLICATION: SystemType.ValueType  # 1
PROCESS_ORCHESTRATOR: SystemType.ValueType  # 2
SESSION_MANAGER: SystemType.ValueType  # 3
RESOURCE_MANAGER: SystemType.ValueType  # 4
AUTHORISER_SERVICE: SystemType.ValueType  # 5
global___SystemType = SystemType

@typing.final
class AuthoriserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    SYSTEM_FIELD_NUMBER: builtins.int
    action: global___ActionType.ValueType
    system: global___SystemType.ValueType
    @property
    def token(self) -> druncmessages.token_pb2.Token: ...
    def __init__(
        self,
        *,
        token: druncmessages.token_pb2.Token | None = ...,
        action: global___ActionType.ValueType = ...,
        system: global___SystemType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["action", b"action", "system", b"system", "token", b"token"]) -> None: ...

global___AuthoriserRequest = AuthoriserRequest
