# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from druncmessages import request_response_pb2 as druncmessages_dot_request__response__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in druncmessages/controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.describe = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/describe',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.status = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/status',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.describe_fsm = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/describe_fsm',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.execute_fsm_command = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/execute_fsm_command',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.execute_expert_command = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/execute_expert_command',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.include = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/include',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.exclude = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/exclude',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.recompute_status = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/recompute_status',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.take_control = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/take_control',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.surrender_control = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/surrender_control',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.who_is_in_charge = channel.unary_unary(
                '/dunedaq.druncmessages.Controller/who_is_in_charge',
                request_serializer=druncmessages_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncmessages_dot_request__response__pb2.Response.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def describe_fsm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def execute_fsm_command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def execute_expert_command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def include(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def exclude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recompute_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def take_control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def surrender_control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def who_is_in_charge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'describe': grpc.unary_unary_rpc_method_handler(
                    servicer.describe,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'status': grpc.unary_unary_rpc_method_handler(
                    servicer.status,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'describe_fsm': grpc.unary_unary_rpc_method_handler(
                    servicer.describe_fsm,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'execute_fsm_command': grpc.unary_unary_rpc_method_handler(
                    servicer.execute_fsm_command,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'execute_expert_command': grpc.unary_unary_rpc_method_handler(
                    servicer.execute_expert_command,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'include': grpc.unary_unary_rpc_method_handler(
                    servicer.include,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'exclude': grpc.unary_unary_rpc_method_handler(
                    servicer.exclude,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'recompute_status': grpc.unary_unary_rpc_method_handler(
                    servicer.recompute_status,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'take_control': grpc.unary_unary_rpc_method_handler(
                    servicer.take_control,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'surrender_control': grpc.unary_unary_rpc_method_handler(
                    servicer.surrender_control,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
            'who_is_in_charge': grpc.unary_unary_rpc_method_handler(
                    servicer.who_is_in_charge,
                    request_deserializer=druncmessages_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncmessages_dot_request__response__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dunedaq.druncmessages.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dunedaq.druncmessages.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/describe',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/status',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def describe_fsm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/describe_fsm',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def execute_fsm_command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/execute_fsm_command',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def execute_expert_command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/execute_expert_command',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def include(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/include',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def exclude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/exclude',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recompute_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/recompute_status',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def take_control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/take_control',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def surrender_control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/surrender_control',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def who_is_in_charge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncmessages.Controller/who_is_in_charge',
            druncmessages_dot_request__response__pb2.Request.SerializeToString,
            druncmessages_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
