"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConfigKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILE_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    file: builtins.str
    session_id: builtins.str
    def __init__(
        self,
        *,
        file: builtins.str = ...,
        session_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["file", b"file", "session_id", b"session_id"]) -> None: ...

global___ConfigKey = ConfigKey

@typing.final
class AllConfigKeys(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONFIG_KEYS_FIELD_NUMBER: builtins.int
    @property
    def config_keys(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ConfigKey]: ...
    def __init__(
        self,
        *,
        config_keys: collections.abc.Iterable[global___ConfigKey] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["config_keys", b"config_keys"]) -> None: ...

global___AllConfigKeys = AllConfigKeys

@typing.final
class ActiveSession(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    USER_FIELD_NUMBER: builtins.int
    CONFIG_KEY_FIELD_NUMBER: builtins.int
    name: builtins.str
    user: builtins.str
    @property
    def config_key(self) -> global___ConfigKey: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        user: builtins.str = ...,
        config_key: global___ConfigKey | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config_key", b"config_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config_key", b"config_key", "name", b"name", "user", b"user"]) -> None: ...

global___ActiveSession = ActiveSession

@typing.final
class AllActiveSessions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTIVE_SESSIONS_FIELD_NUMBER: builtins.int
    @property
    def active_sessions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ActiveSession]: ...
    def __init__(
        self,
        *,
        active_sessions: collections.abc.Iterable[global___ActiveSession] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["active_sessions", b"active_sessions"]) -> None: ...

global___AllActiveSessions = AllActiveSessions
