"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FSMStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    SUB_STATE_FIELD_NUMBER: builtins.int
    IN_ERROR_FIELD_NUMBER: builtins.int
    INCLUDED_FIELD_NUMBER: builtins.int
    state: builtins.str
    sub_state: builtins.str
    in_error: builtins.bool
    included: builtins.bool
    def __init__(
        self,
        *,
        state: builtins.str = ...,
        sub_state: builtins.str = ...,
        in_error: builtins.bool = ...,
        included: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["in_error", b"in_error", "included", b"included", "state", b"state", "sub_state", b"sub_state"]) -> None: ...

global___FSMStatus = FSMStatus

@typing.final
class CommandTime(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CMD_START_TIME_FIELD_NUMBER: builtins.int
    CMD_EXECUTION_TIME_FIELD_NUMBER: builtins.int
    cmd_start_time: builtins.int
    cmd_execution_time: builtins.int
    def __init__(
        self,
        *,
        cmd_start_time: builtins.int = ...,
        cmd_execution_time: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cmd_execution_time", b"cmd_execution_time", "cmd_start_time", b"cmd_start_time"]) -> None: ...

global___CommandTime = CommandTime
