# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: druncschema/opmon/opmon_FSM.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'druncschema/opmon/opmon_FSM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!druncschema/opmon/opmon_FSM.proto\x12\x13\x64unedaq.drunc.opmon\"Q\n\tFSMStatus\x12\r\n\x05state\x18\x01 \x01(\t\x12\x11\n\tsub_state\x18\x02 \x01(\t\x12\x10\n\x08in_error\x18\x03 \x01(\x08\x12\x10\n\x08included\x18\x04 \x01(\x08\")\n\x0b\x43ommandTime\x12\x1a\n\x12\x63md_execution_time\x18\x01 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'druncschema.opmon.opmon_FSM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FSMSTATUS']._serialized_start=58
  _globals['_FSMSTATUS']._serialized_end=139
  _globals['_COMMANDTIME']._serialized_start=141
  _globals['_COMMANDTIME']._serialized_end=182
# @@protoc_insertion_point(module_scope)
