"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RunInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RUN_TYPE_FIELD_NUMBER: builtins.int
    TRIGGER_RATE_FIELD_NUMBER: builtins.int
    RUN_NUMBER_FIELD_NUMBER: builtins.int
    DISABLE_DATA_STORAGE_FIELD_NUMBER: builtins.int
    run_type: builtins.str
    trigger_rate: builtins.float
    run_number: builtins.int
    disable_data_storage: builtins.bool
    def __init__(
        self,
        *,
        run_type: builtins.str = ...,
        trigger_rate: builtins.float = ...,
        run_number: builtins.int = ...,
        disable_data_storage: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["disable_data_storage", b"disable_data_storage", "run_number", b"run_number", "run_type", b"run_type", "trigger_rate", b"trigger_rate"]) -> None: ...

global___RunInfo = RunInfo

@typing.final
class ProcessStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    N_RUNNING_FIELD_NUMBER: builtins.int
    N_DEAD_FIELD_NUMBER: builtins.int
    N_SESSION_FIELD_NUMBER: builtins.int
    n_running: builtins.int
    n_dead: builtins.int
    n_session: builtins.int
    def __init__(
        self,
        *,
        n_running: builtins.int = ...,
        n_dead: builtins.int = ...,
        n_session: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["n_dead", b"n_dead", "n_running", b"n_running", "n_session", b"n_session"]) -> None: ...

global___ProcessStatus = ProcessStatus
