# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from druncschema import broadcast_pb2 as druncschema_dot_broadcast__pb2
from druncschema import generic_pb2 as druncschema_dot_generic__pb2
from druncschema import request_response_pb2 as druncschema_dot_request__response__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in druncschema/broadcast_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BroadcastReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.handle_broadcast = channel.unary_unary(
                '/dunedaq.druncschema.BroadcastReceiver/handle_broadcast',
                request_serializer=druncschema_dot_broadcast__pb2.BroadcastMessage.SerializeToString,
                response_deserializer=druncschema_dot_generic__pb2.Empty.FromString,
                _registered_method=True)


class BroadcastReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def handle_broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BroadcastReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'handle_broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.handle_broadcast,
                    request_deserializer=druncschema_dot_broadcast__pb2.BroadcastMessage.FromString,
                    response_serializer=druncschema_dot_generic__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dunedaq.druncschema.BroadcastReceiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dunedaq.druncschema.BroadcastReceiver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BroadcastReceiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def handle_broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncschema.BroadcastReceiver/handle_broadcast',
            druncschema_dot_broadcast__pb2.BroadcastMessage.SerializeToString,
            druncschema_dot_generic__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BroadcastSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_to_broadcast_list = channel.unary_unary(
                '/dunedaq.druncschema.BroadcastSender/add_to_broadcast_list',
                request_serializer=druncschema_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncschema_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.remove_from_broadcast_list = channel.unary_unary(
                '/dunedaq.druncschema.BroadcastSender/remove_from_broadcast_list',
                request_serializer=druncschema_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncschema_dot_request__response__pb2.Response.FromString,
                _registered_method=True)
        self.get_broadcast_list = channel.unary_unary(
                '/dunedaq.druncschema.BroadcastSender/get_broadcast_list',
                request_serializer=druncschema_dot_request__response__pb2.Request.SerializeToString,
                response_deserializer=druncschema_dot_request__response__pb2.Response.FromString,
                _registered_method=True)


class BroadcastSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_to_broadcast_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove_from_broadcast_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_broadcast_list(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BroadcastSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_to_broadcast_list': grpc.unary_unary_rpc_method_handler(
                    servicer.add_to_broadcast_list,
                    request_deserializer=druncschema_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncschema_dot_request__response__pb2.Response.SerializeToString,
            ),
            'remove_from_broadcast_list': grpc.unary_unary_rpc_method_handler(
                    servicer.remove_from_broadcast_list,
                    request_deserializer=druncschema_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncschema_dot_request__response__pb2.Response.SerializeToString,
            ),
            'get_broadcast_list': grpc.unary_unary_rpc_method_handler(
                    servicer.get_broadcast_list,
                    request_deserializer=druncschema_dot_request__response__pb2.Request.FromString,
                    response_serializer=druncschema_dot_request__response__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dunedaq.druncschema.BroadcastSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dunedaq.druncschema.BroadcastSender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BroadcastSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_to_broadcast_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncschema.BroadcastSender/add_to_broadcast_list',
            druncschema_dot_request__response__pb2.Request.SerializeToString,
            druncschema_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def remove_from_broadcast_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncschema.BroadcastSender/remove_from_broadcast_list',
            druncschema_dot_request__response__pb2.Request.SerializeToString,
            druncschema_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_broadcast_list(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dunedaq.druncschema.BroadcastSender/get_broadcast_list',
            druncschema_dot_request__response__pb2.Request.SerializeToString,
            druncschema_dot_request__response__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
