"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import druncschema.request_response_pb2
import druncschema.token_pb2
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommandDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_TYPE_FIELD_NUMBER: builtins.int
    HELP_FIELD_NUMBER: builtins.int
    RETURN_TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    help: builtins.str
    return_type: builtins.str
    @property
    def data_type(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        data_type: collections.abc.Iterable[builtins.str] | None = ...,
        help: builtins.str = ...,
        return_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data_type", b"data_type", "help", b"help", "name", b"name", "return_type", b"return_type"]) -> None: ...

global___CommandDescription = CommandDescription

@typing.final
class OldDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    COMMANDS_FIELD_NUMBER: builtins.int
    BROADCAST_FIELD_NUMBER: builtins.int
    type: builtins.str
    name: builtins.str
    endpoint: builtins.str
    info: builtins.str
    session: builtins.str
    @property
    def commands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CommandDescription]: ...
    @property
    def broadcast(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        name: builtins.str = ...,
        endpoint: builtins.str = ...,
        info: builtins.str | None = ...,
        session: builtins.str | None = ...,
        commands: collections.abc.Iterable[global___CommandDescription] | None = ...,
        broadcast: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_broadcast", b"_broadcast", "_info", b"_info", "_session", b"_session", "broadcast", b"broadcast", "info", b"info", "session", b"session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_broadcast", b"_broadcast", "_info", b"_info", "_session", b"_session", "broadcast", b"broadcast", "commands", b"commands", "endpoint", b"endpoint", "info", b"info", "name", b"name", "session", b"session", "type", b"type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_broadcast", b"_broadcast"]) -> typing.Literal["broadcast"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_info", b"_info"]) -> typing.Literal["info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_session", b"_session"]) -> typing.Literal["session"] | None: ...

global___OldDescription = OldDescription

@typing.final
class NewDescription(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    SESSION_FIELD_NUMBER: builtins.int
    COMMANDS_FIELD_NUMBER: builtins.int
    BROADCAST_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    type: builtins.str
    name: builtins.str
    endpoint: builtins.str
    info: builtins.str
    session: builtins.str
    flag: druncschema.request_response_pb2.ResponseFlag.ValueType
    @property
    def commands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CommandDescription]: ...
    @property
    def broadcast(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[druncschema.request_response_pb2.Response]: ...
    @property
    def token(self) -> druncschema.token_pb2.Token: ...
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        name: builtins.str = ...,
        endpoint: builtins.str = ...,
        info: builtins.str | None = ...,
        session: builtins.str | None = ...,
        commands: collections.abc.Iterable[global___CommandDescription] | None = ...,
        broadcast: google.protobuf.any_pb2.Any | None = ...,
        children: collections.abc.Iterable[druncschema.request_response_pb2.Response] | None = ...,
        flag: druncschema.request_response_pb2.ResponseFlag.ValueType = ...,
        token: druncschema.token_pb2.Token | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_broadcast", b"_broadcast", "_info", b"_info", "_session", b"_session", "broadcast", b"broadcast", "info", b"info", "session", b"session", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_broadcast", b"_broadcast", "_info", b"_info", "_session", b"_session", "broadcast", b"broadcast", "children", b"children", "commands", b"commands", "endpoint", b"endpoint", "flag", b"flag", "info", b"info", "name", b"name", "session", b"session", "token", b"token", "type", b"type"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_broadcast", b"_broadcast"]) -> typing.Literal["broadcast"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_info", b"_info"]) -> typing.Literal["info"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_session", b"_session"]) -> typing.Literal["session"] | None: ...

global___NewDescription = NewDescription
