# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: druncschema/generic.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'druncschema/generic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x64runcschema/generic.proto\x12\x16\x64unedaq.drunc_messages\"\x07\n\x05\x45mpty\"\x19\n\tPlainText\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\x0fPlainTextVector\x12\x0c\n\x04text\x18\x01 \x03(\t\"\x1a\n\nStacktrace\x12\x0c\n\x04text\x18\x01 \x03(\t\"|\n\x0fStringStringMap\x12=\n\x03map\x18\x01 \x03(\x0b\x32\x30.dunedaq.drunc_messages.StringStringMap.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x18\n\x07int_msg\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1a\n\tfloat_msg\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1b\n\nstring_msg\x12\r\n\x05value\x18\x01 \x01(\t\"\x19\n\x08\x62ool_msg\x12\r\n\x05value\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'druncschema.generic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGSTRINGMAP_MAPENTRY']._loaded_options = None
  _globals['_STRINGSTRINGMAP_MAPENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=53
  _globals['_EMPTY']._serialized_end=60
  _globals['_PLAINTEXT']._serialized_start=62
  _globals['_PLAINTEXT']._serialized_end=87
  _globals['_PLAINTEXTVECTOR']._serialized_start=89
  _globals['_PLAINTEXTVECTOR']._serialized_end=120
  _globals['_STACKTRACE']._serialized_start=122
  _globals['_STACKTRACE']._serialized_end=148
  _globals['_STRINGSTRINGMAP']._serialized_start=150
  _globals['_STRINGSTRINGMAP']._serialized_end=274
  _globals['_STRINGSTRINGMAP_MAPENTRY']._serialized_start=232
  _globals['_STRINGSTRINGMAP_MAPENTRY']._serialized_end=274
  _globals['_INT_MSG']._serialized_start=276
  _globals['_INT_MSG']._serialized_end=300
  _globals['_FLOAT_MSG']._serialized_start=302
  _globals['_FLOAT_MSG']._serialized_end=328
  _globals['_STRING_MSG']._serialized_start=330
  _globals['_STRING_MSG']._serialized_end=357
  _globals['_BOOL_MSG']._serialized_start=359
  _globals['_BOOL_MSG']._serialized_end=384
# @@protoc_insertion_point(module_scope)
