# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opmon.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bopmon.proto\x12\rdunedaq.opmon\"c\n\x07RunInfo\x12\x10\n\x08run_type\x18\x01 \x01(\t\x12\x14\n\x0ctrigger_rate\x18\x02 \x01(\x01\x12\x12\n\nrun_number\x18\x03 \x01(\x03\x12\x1c\n\x14\x64isable_data_storage\x18\x04 \x01(\x08\"N\n\x06Status\x12\r\n\x05state\x18\x02 \x01(\t\x12\x11\n\tsub_state\x18\x03 \x01(\t\x12\x10\n\x08in_error\x18\x04 \x01(\x08\x12\x10\n\x08included\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opmon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RUNINFO']._serialized_start=30
  _globals['_RUNINFO']._serialized_end=129
  _globals['_STATUS']._serialized_start=131
  _globals['_STATUS']._serialized_end=209
# @@protoc_insertion_point(module_scope)
